### ISSUE TITLE
Found pants error when reinstalling after remove Backend.AI

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai#1046]
### What Operating System(s) are you seeing this problem on?

Apple M1 (aarch64)

### Backend.AI version

main

### Describe the bug

For the first time, I get Backend.AI repo and installed it.

However, I try to delete and reinstall Backend.AI.

When reinstalling after remove Backend.AI, I found pants error. 

below is pants error log
```console
[INFO] Installing Python...
✓ Python 3.9.16 as the Pants runtime is already installed.
✓ Python 3.10.9 as the Backend.AI runtime is already installed.

[INFO] Checking Python features...
SSL support: ok
LZMA support: ok

[INFO] Bootstrapping the Pants build system...
Chosen Python 3.9.16 (from pyenv) as the local Pants interpreter
2.16.0.dev5

[INFO] Using the current working-copy directory as the installation path...

[INFO] Creating the unified virtualenv for IDEs...
14:42:06.06 [INFO] Completed: Build pex for resolve `python-kernel`
14:42:06.06 [INFO] Completed: Build pex for resolve `python-default`
14:42:06.06 [ERROR] 1 Exception encountered:

Engine traceback:
  in `export` goal

IntrinsicError: No such file or directory (os error 2)
```
<img width="845" alt="image" src="https://user-images.githubusercontent.com/20002/218385171-6d16431a-47e0-47c2-b14e-af3239529f0e.png">

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/20002/218385067-2b5b8e58-2377-4fb0-9894-89e3a3632c61.png">

By the way, I modify install-dev.sh and reinstall Backend.AI, It works successfully.
Below is modified install-dev.sh diff
```diff
diff --git a/scripts/install-dev.sh b/scripts/install-dev.sh
index b8f3b489..a4282552 100755
--- a/scripts/install-dev.sh
+++ b/scripts/install-dev.sh
@@ -645,7 +645,7 @@ setup_environment() {
   show_info "Using the current working-copy directory as the installation path..."

   show_info "Creating the unified virtualenv for IDEs..."
-  $PANTS export \
+  $PANTS --print-stacktrace export \
     --resolve=python-default \
     --resolve=python-kernel \
     --resolve=pants-plugins \
```

 I don't understand that Backend.AI installation will take place only after adding the additional debug argument '--print-stacktrace' to 'install-dev.sh',  when reinstalling after remove Backend.AI

**Comment by studioego** [comment]
I checked both Apple M1 and Linux(aarch - Ubuntu 22.04, x86_64 - Fedora Core 37).
It occurs only Apple M1 platform.

**Comment by achimnol** [comment]
Is it still valid? I suspect this may be a side effect of configuration issues or already fixed by pants updates.

**Comment by studioego** [comment]
I checked Backend.AI repos.
One is Backend.AI's origin/main repo. It works.  (pants version: 2.16.0.dev7)
The other is Backend.AI's WIP repo https://github.com/lablup/backend.ai/tree/feature/add-git-token-management 
I saw the pants installing error.
![image](https://user-images.githubusercontent.com/20002/230965010-c77796df-f75a-47a5-bf36-23b99a242113.png)

```shell
[INFO] Creating the unified virtualenv for IDEs...
00:58:03.74 [ERROR] 1 Exception encountered:

 

Engine traceback:
  in `export` goal

 

IntrinsicError: Failed to create a temporary directory for materialization of immutable input digest Digest { hash: Fingerprint<2646c982e908cb3a2b0e4149878a4658539e8e2e6dde2534aeb573be1b0ebdf9>, size_bytes: 4075440 }: No such file or directory (os error 2) at path "/Users/dhsung/bai-dev/.tmp/immutable_inputsY8ToNn/.tmpC5FA5P"
```

However, I merged from origin/main repo, It also works. (pants version: 2.16.0.dev7)

As a result, I close the issue because it cannot be reproduced when you update the Backend.AI repo to the latest.
