### ISSUE TITLE
Install error about OS

### ISSUE THREAD

**Issue by VTVoo** [lablup/backend.ai#105]
I'm using 'Ubuntu wsl' (ubuntu on windows10).
And tried to install backend.ai by executing command 'sh install-dev.sh', but got an error like below. Distributor ID is 'Ubuntu' and version is 18.04 from 'lsb_release -a'
Let me know how to install it. 
Thanks.

-----------------------------------------------------------------------------------------
install-dev.sh: 4: install-dev.sh: shopt: not found
install-dev.sh: 96: install-dev.sh: [[: not found
install-dev.sh: 117: [: Ubuntu: unexpected operator
install-dev.sh: 119: [: Ubuntu: unexpected operator
install-dev.sh: 121: [: Ubuntu: unexpected operator

[ERROR] Sorry, your host OS distribution is not supported by this script.

**Comment by kyujin-cho** [comment]
try `bash` instead of `sh`.

**Comment by achimnol** [comment]
This should be resolved by following @kyujin-cho's answer.
Please reopen if you have further installation issues or questions.

**Comment by VTVoo** [comment]
Thank you for helping :)
