### ISSUE TITLE
Install error about Docker

### ISSUE THREAD

**Issue by VTVoo** [lablup/backend.ai#109]
I tried to install program in Ubuntu 18.04 LTS (on windows10), but it was failed.
I followed steps below and got the error.

**1. when first install**

***Steps** 
 - git init
 - git clone <backend.ai metarepo>
 - bash install-dev.sh

***Error**
```
Err:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
Hash Sum mismatch
...
Err:7 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
  
Fetched 2128 kB in 5s (395 kB/s)
Reading package lists... Done
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-amd64/by-hash/SHA256/c9dd368cc6f105daccf530a5cc81173a10c09adcf1e0091c3b5fb0068a04b9c1  Hash Sum mismatch
 ...
[INFO] Creating the install directory...
[INFO] Launching the docker-compose "halfstack"...
Cloning into 'backend.ai'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 1960 (delta 46), reused 40 (delta 10), pack-reused 1847
Receiving objects: 100% (1960/1960), 719.14 KiB | 903.00 KiB/s, done.
Resolving deltas: 100% (1174/1174), done.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
 
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

**2. when trying install after fail**

***Steps**
- same

***Error**
```
Err:5 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
Hash Sum mismatch
 ...
Err:7 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
 
Fetched 2128 kB in 5s (395 kB/s) Reading package lists... Done
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/binary-amd64/by-hash/SHA256/c9dd368cc6f105daccf530a5cc81173a10c09adcf1e0091c3b5fb0068a04b9c1  Hash Sum mismatch
 ...
[INFO] Creating the install directory...
  
[INFO] Launching the docker-compose "halfstack"...
fatal: destination path 'backend.ai' already exists and is not an empty directory.
```
------------------------------------------------------------------------------------------
p.s : Docker terminal seems to run well. Some cammands like 'pull', 'attach' work.
#

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1159751085623729/1159756728317528) by [Unito](https://www.unito.io/learn-more)

**Comment by achimnol** [comment]
How did you install the Docker service?

**Comment by achimnol** [comment]
Also, please [use backticks or triple-backtickss to quote terminal outputs and source codes](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) to make your posts readable.

**Comment by VTVoo** [comment]
I installed docker toolbox(Kitematic + Docker Quickstart Terminal)

**Comment by VTVoo** [comment]
I changed OS from Windows10 home to Ubuntu 18.04, and got a same problem.
In this time, deleted all 'backend.ai' folders and '.git' folder, and problem was solved.

**Comment by jungyh0218** [comment]
I got the same issue while re-installing backend.ai. It is necessary to remove docker containers and relevant docker images before installation.
