### ISSUE TITLE
How to active GPU contents ?

### ISSUE THREAD

**Issue by ChaejinE** [lablup/backend.ai#1140]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

22.09.16

### Describe the bug

I didn't see amount of  GPUs. 
How to active this contents like your main page ?

![image](https://user-images.githubusercontent.com/69780812/223616302-55a82637-9339-4422-ae73-c74e8d961f20.png)
(my)

![image](https://user-images.githubusercontent.com/69780812/223616322-99d0244a-e792-4d10-8941-ea3fb1c4436d.png)
(yours)

**Comment by achimnol** [comment]
You need to enable the CUDA plugins. In this repository, there are two variants: `ai.backend.accelerator.cuda_open` and `ai.backend.accelerator.cuda_mock`.

- `cuda_open` supports per-device assignment on containers.
- `cuda_mock` provides an emulation of CUDA devices to the agent and manager to allow development and testing of the scheduler and the webui without actual CUDA devices.

In a development setup, you can enable them by setting `agent.toml` as follows, and restarting the agent:

```toml
[agent]
allow-compute-plugins = ["ai.backend.accelerator.cuda_open"]
```

Of course, your host and container images should have a working NVIDIA driver and CUDA driver/runtime installations.
