### ISSUE TITLE
pants --changed-dependees option will be deprecated soon and should be replaced

### ISSUE THREAD

**Issue by Yaminyam** [lablup/backend.ai#1218]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

22.09

### Describe the bug

https://www.pantsbuild.org/v2.16/docs/reference-changed#deprecated-options
```
05:09:17.81 [WARN] DEPRECATED: option 'dependees' in scope 'changed' is scheduled to be removed in version 2.23.0.dev0.

Use --dependents instead
```

The --changed-dependees option of pants will be removed starting with version 2.23.0 and should be replaced with the --dependents option.

**Comment by achimnol** [comment]
I'm trying the new option in #1281.
