### ISSUE TITLE
Invalid vfolder mount target path

### ISSUE THREAD

**Issue by fregataa** [lablup/backend.ai#1323]
Currently, it is possible to assign mount target path that includes a comma such as `C:/hello`.
but such mount path occurs error because we use `:` as a delimeter of vfolder's source path, target path and permission like this `/src/hello:/trg/hello:rw`.
Let's block such target path or please suggest any idea.

**Comment by achimnol** [comment]
Maybe we could force conversion to `pathlib.PosixPath` before interpolating the vfolder mount expression.

**Comment by achimnol** [comment]
To distinguish if the given string is a Windows path or not, we could use the following sample: https://chat.openai.com/share/75f57f32-c9fe-4faa-b6af-ffb450fabed4

But, in this case, we need to generally *escape* the colons in the path components as colons are invalid in Windows filenames but valid in Linux filenames.
