### ISSUE TITLE
Cannot add AWS ECR registry to use custom container images

### ISSUE THREAD

**Issue by iv0rish** [lablup/backend.ai#1388]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

23.03.9.dev0

### Describe the bug

Not only AWS ECR, I cannot add container registry which includes numeric or special characters like hypen or underscore due to below pattern at `configure-registry-url` textfield. 

```
^(https?)://(([a-zA-Zd.]{2,}).([a-zA-Z]{2,})|(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3})(:((6553[0-5])|(655[0-2])|(65[0-4][0-9]{2})|(6[0-4][0-9]{3})|([1-5][0-9]{4})|([0-5]{0,5})|([0-9]{1,4})))?$
```

### To Reproduce

Try to add registry in webui or desktop app

**Comment by achimnol** [comment]
Thanks for the report. I think we should improve the input validation for the registry URLs.

**Comment by achimnol** [comment]
Done!
