### ISSUE TITLE
Make it available to create a project folder regardless of `max_vfolder_count`.

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai#1391]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

23.03

### Describe the bug

If a number of created user vfolder is the same as `max_vfolder_count`, the admin cannot create a new project folder.
The number of project folder limit should be related to the `ProjectResourcePolicy` not `KeypairResourcePolicy`.

So let's make it available to create a project folder regardless of `max_vfolder_count`. 
If possible, let's add `max_vfolder_count` to the `ProjectResourcePolicy` and limit the number of creating project folders using that.

### To Reproduce

Create as many user folders as `max_vfolder_count` and create a project folder. A new project folder cannot be created, even though it must be created regardless of `max_vfolder_count`.

### Expected Behavior

Project folder should be created.

**Comment by Sujin-Kim1** [comment]
Dongjin Park will handle this.

**Comment by achimnol** [comment]
This was supposed to be handled as part of #384.
This issue should be resolved first and then we need to work on #1392.
