### ISSUE TITLE
Fix sentinel connection pool usage in `common.redis_helper`

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#1564]
[According to the docs](https://redis-py.readthedocs.io/en/v4.6.0/connections.html#redis.Redis), `redis.Redis` can be initialized with either a conenction or a connection pool. In the same way, [the `master_for()` function](https://redis-py.readthedocs.io/en/v4.6.0/connections.html#redis.sentinel.Sentinel.master_for) returns a Redis instance with a sentinel connection pool.

As @jopemachine has discovered, our current design does not conform with the intended usage of the sentinel connection pool.:
* `common.redis_helper.get_redis_object()` returns `RedisConnectionInfo`.
* `common.redis_helper.execute()` uses it to create a Redis instance by calling `master_for()` directly.
* `common.redis_helper.execute()` executes `async with r: ...` to auto-close the underlying connection after use, but this does *NOT* close the connection pool by default.
* Until properly garbage-collected, the underlying sentinel connection pool may keep several open but unused connections, and yet another `execute()` invocation before gc may accumulate the Redis connection counts indefinitely.

Connection pools are intended to be kept alive across the entire lifecycle of the host process or thread. So we need to change the design as follows:
* `common.redis_helper.get_redis_object()` to return `Redis` instances with an appropriate backing connection pool.
* `common.redis_helper.execute()` should reuse the `Redis` instance taken from a global context (maybe `RootContext` in the Manager -- we can initialize them in `manager.server.redis_ctx`) instead of create the connection pool everytime.
  - Since `common` should be decoupled from `manager` and `agent`, the context management should be done in the `agent` and `manager` side while the `common` API should take the Redis instance only.

Additional concerns:
* Since `Redis` interface abstracts the underlying connection details away, it may be better to use explicit variable namings like `redis_conn` or `redis_connpool` when referring a `Redis` instance to indicate how it is backed.
* Each blocking redis command such as `BLPOP`, `XREAD`, `XREADGROUP` consumes and occupies a connection from the pool indefinitely. The connection pool size must be larger than the maximum concurrent invocations of the blocking command, or we need to separate the connection/connection pool for them.

NOTE: This redesign will involve rewriting of the test codes in `tests/common/redis_helper`.

This issue should be resolved together with #1443.

**Comment by jopemachine** [comment]
This should be closed as https://github.com/lablup/backend.ai/pull/1586 is merged
