### ISSUE TITLE
Let's query folder info both vfolder name and uuid

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai#1569]
### Main idea

For now, it is available to get vfolder info by just the name. Let's allow query with vfolder uuid so that the client gets the vfolder info using vfolder uuid.

### Alternative ideas

Add a new API named `info_by_id` or something.

**Comment by fregataa** [comment]
https://github.com/lablup/backend.ai/pull/432
This PR implements query vfolder gql by id

**Comment by fregataa** [comment]
closed by #432
