### ISSUE TITLE
Manager cannot handle requests when user/group is not root in some environments

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#157]
In `manager.toml`, we can set `user` and `group` for the manager daemon. In some environments (such as H-company), specifying these values except `-1` raises an exception upon client request. The traceback indicated there's some problems in parsing manager's api address, which does not seem to be related to the manager daemon's ownership.

<img width="846" alt="스크린샷 2019-09-06 오후 1 51 13" src="https://user-images.githubusercontent.com/7539358/64401967-3266de00-d0ae-11e9-9930-4800db6a2f0e.png">

Steps to reproduce:
* Connect to H-company's VDI.
* Open manager server's ssh.
* Edit `manager.toml` and change `user` and `group` to `"lablup"` or `<uid-of-lablup>`.
* Restart manager.
* Send request to manager with any of client-py, console app, and/or hub.
* During processing the request, the exception above occurs.

**Comment by achimnol** [comment]
Cannot reproduce it anymore. Let's just keep it as a record.
