### ISSUE TITLE
console-server: Support API KeyPair authentication

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai#159]
Proxy for tunneling APIKey-based request

 * [ ] Request-only address based on API key.
 * [ ] Routines to bypass API key based requests.
 * [ ] Option to enable or disable the address that receives API key based requests.

Requested by users with CLI.

**Comment by achimnol** [comment]
This is replaced with #523.

**Comment by achimnol** [comment]
When keypair-based manager API access is required (e.g., bots), use the manager endpoint directly.
