### ISSUE TITLE
Wrong etcd connection blocks storage proxy with weird log output

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai#1598]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

23.09b2

### Describe the bug

When etcd connection is blocked or port configuration is wrong, storage proxy fails to start with weird error log output.

<img width="1063" alt="image" src="https://github.com/lablup/backend.ai/assets/949915/41209ff2-261d-46ac-b5f4-745e9f2707ae">

### To Reproduce

1. Turn off etcd / or change port information in storage-proxy.toml to point wrong number
2. Start storage proxy

### Expected Behavior

It should shows proper error log, not a log with AioRpcError log with failed pickle output.

**Comment by achimnol** [comment]
Ultimately, we need a multi-process-safe non-blocking logging mechanism that does not use `pickle` in the "relay" log handler to prevent long garbled outputs like this when the exception is not picklable.

For now, we need to catch the underlying grpcio exeception and add a custom logic to distinguish the class of exceptions, either in `etcetra` or in `ai.backend.common.etcd`.
