### ISSUE TITLE
How do I setup key in on-premise

### ISSUE THREAD

**Issue by FuZer** [lablup/backend.ai#16]
I've set up backend.ai (manager, agent, client) to local server.
Then, I've set up `BACKEND_ENDPOINT` for client. 

but I didn't found key for my local manager.
`BACKEND_ACCESS_KEY`
`BACKEND_SECRET_KEY`

Where can I find/setting them?

**Comment by FuZer** [comment]
I just search the code and found python -m ai.backend.gateway.auth --generate-keypair

**Comment by achimnol** [comment]
That command is for generating a keypair in CLI, without registering to the keypair database.
Please have a look at [the installation manual](https://github.com/lablup/backend.ai/wiki).
In particular, check out [the database initialization process](https://github.com/lablup/backend.ai/wiki/Prepare-Databases-for-Manager#load-initial-fixtures) to specify initial keypairs.

**Comment by FuZer** [comment]
Oh yes, I does not check example keypair.
I close this issue.
Thanks.
