### ISSUE TITLE
Let's add a link for each row in routings list that connects to session page

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai#1618]
### Main idea

Currently, the only way to check session corresponding to the routings in model-service is referring to each session name, which degrades the user experience. It's better to provide a link so that user could get an access for routing more easily.

- [ ] Provide a link for each session in routings list (perhaps applying it to session ID column)
- [ ] Show only the corresponding session by using name-filtering.

### Screenshot(s)
<img width="1159" alt="Screenshot 2023-10-13 at 2 44 05 PM" src="https://github.com/lablup/backend.ai/assets/46954439/2aafe5e7-f9f0-4026-ab4a-fde9b9c8d9c3">

**Comment by yomybaby** [comment]
After https://github.com/lablup/backend.ai-webui/pull/2775 , user can open a session detail drawer by clicking session id in a endpoint's routing list. 
If the GraphQL type related to the endpoint is changed to a Relay Node type, it will be easier to improve the UX. ;)

I close this issue.
