### ISSUE TITLE
Add `backend.ai mgr upgrade` command

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#1682]
Let's add a manager CLI command `mgr upgrade` to do auto-upgrade the backing databases, such as invoking `alembic upgrade head`.

**Comment by gpuligundla** [comment]
Hi @achimnol, can I work on this?

**Comment by achimnol** [comment]
> Hi joongi (@achimnol), can I work on this?

Ah, this will be included as an extension of #1694 in the future, in the "MAINTAIN" menu.
Closing in favor of #1694. Sorrry!
