### ISSUE TITLE
Cannot query keypair list after creating a new user

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai#1703]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

23.09

### Describe the bug

If the admin creates a new user with setting project, it's not possible to query keypair list with the below error.
`
BackendAPIError(400, 'Bad request', {'type': '[https://api.backend.ai/probs/graphql-error'](https://api.backend.ai/probs/graphql-error%27), 'title': 'GraphQL-generated error', 'data': [OrderedDict([('message', "'<=' not supported between instances of 'str' and 'int'"), ('locations', [OrderedDict([('line', 3), ('column', 79)])]), ('path', ['keypair_list', 'items', 5, 'concurrency_used'])]), OrderedDict([('message', "'<=' not supported between instances of 'str' and 'int'"), ('locations', [OrderedDict([('line', 3), ('column', 107)])]), ('path', ['keypair_list', 'items', 5, 'num_queries'])])]})
`
<img width="569" alt="image" src="https://github.com/lablup/backend.ai/assets/28584164/4714a45d-21d9-4229-934b-99973f824747">

### To Reproduce

Create a new user by specifying a project and look up the key pair list.

### Expected Behavior

return keypair list

**Comment by gpuligundla** [comment]
trying to triage the issue

**Comment by minseokey** [comment]
@agatha197 I'm trying to solve this issue now, but it's hard to create the same problem situation. How did the error occur?

**Comment by agatha197** [comment]
@minseokey already resolved. close this issue.
