### ISSUE TITLE
Fractional GPU sharing and Security concerns.

### ISSUE THREAD

**Issue by felipeblazing** [lablup/backend.ai#173]
**Describe the bug**
Right now the only technology we have seen that allows GPU fractional sharing is https://www.nvidia.com/en-us/data-center/virtual-gpu-technology/ and it doesn't just work on any server. There are specific vendors that have made this available. How are you able to divide up the GPU resources among users and make sure that they can access each others memory?

**Additional context**
We are really interested in helping one of our clients divide up resources fractionally and wanted to get some more information on how backend.ai does this and seeing if it would be possible to leverage your offering to provide this value to our client.

**Comment by achimnol** [comment]
In short, we hook CUDA runtime-to-driver API calls and apply resource constraints based on API parameters and return values. This has the same security level of uncontainerized multi-process GPU access scenario: multiple user-level processes share the same CUDA driver and the GPU but accesses happen via different driver contexts. We keep the driver and runtime contexts intact as user processes create and use but only enforces resource limits.

**Comment by achimnol** [comment]
Closing the issue since this is a simple question.
Please feel free to reopen this issue or create another issue if you have further questions.
