### ISSUE TITLE
Store `list` in `AsyncEtcd`

### ISSUE THREAD

**Issue by fregataa** [lablup/backend.ai#1772]
### Main idea

Currently, `ai.backend.common.etcd.AsyncEtcd` cannot store and retrieve `list` type data. We need a list data serializer so that we can store and retrieve data with complex structures in `AsyncEtcd`.

### Anything else?

[etcd3 API `PUT`](https://etcd.io/docs/v3.2/learning/api/#put) does not support to store `array` value. We need to discuss further how we should store array type data.

**Comment by achimnol** [comment]
This is superseded by #1870 and improved trafaret checks in the container registries (#1471), but now they are also being migrated to Postgres (#1907).
