### ISSUE TITLE
Enhance GraphQL documentation

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#1782]
* [ ] **webserver:** Embed the GraphiQL interface for live schema introspection
  - Activate this only when `config/api/allow-graphql-schema-introspection` (etcd) configuration is on (see also: #1632)
* [ ] **docs:** Auto-generate the list of queries and mutations from the [ai.backend.manager.models.gql](https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/models/gql.py) module as a GraphQL reference
  - Include a mention to the webserver's GraphiQL viewer.

**Comment by achimnol** [comment]
Consider using: https://github.com/wayfair/dociql?tab=readme-ov-file 
(Demo: https://wayfair.github.io/dociql/ )
Idea by @yomybaby

**Comment by yomybaby** [comment]
https://github.com/anvilco/spectaql 
This looks better. @achimnol
