### ISSUE TITLE
delete-dev.sh does not delete database

### ISSUE THREAD

**Issue by Yaminyam** [lablup/backend.ai#1802]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

main

### Describe the bug

https://github.com/lablup/backend.ai/blob/8ef6fdd0dae39f499dc3e3f7c363be103e0f175a/scripts/install-dev.sh#L221C59-L221C59
According to the output of install-dev.sh, delete-dev.sh deletes the database.
However, even if delete-dev.sh is actually executed, all contents of volumes remain.

**Comment by achimnol** [comment]
This will be handled in the new installer project, but I think it would be handled as an option in `delete-dev.sh` in the meanwhile.
