### ISSUE TITLE
Allow modification of inference session resource params preserving endpoints

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#1848]
Let's allow modification of the resource configuration (e.g., the number of CPU cores and GPUs) used by each container of existing service endpoints, without recreating the entire endpoints but just applying the new configuration from the newly spawned containers.

This way, we could allow our users to change the resource configs and applying them by shrinking/expanding the desired routing count on the fly.

For now, let's allow changing the resource slots only.
We could consider changing resource groups and other attributes as well, but we need to discuss potential side-effects of them and how we could present the scenarios to the users without intimidating them.

**Comment by lizable** [comment]
We need implementation on GQL and REST API also, to support both client-side (Backend.AI WebUI and Backend.AI CLI).
