### ISSUE TITLE
Keypair data and count mismatch issues

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai#1861]
### Main idea

The `keypair_list` returns only 7 user data, but the count is 14.
It looks like because of the mismatch between keypair list's `items` and `total_count` query.
Let's sync up both data.
<img width="619" alt="image" src="https://github.com/lablup/backend.ai/assets/28584164/8f7ea3d1-2184-4381-9c14-a73f2d2d5d49">
<img width="232" alt="image" src="https://github.com/lablup/backend.ai/assets/28584164/0f3b6374-c765-4fe5-b5c6-48d5410dca2b">

related issue: https://github.com/lablup/backend.ai/issues/1703

### Alternative ideas

It can be resolved using [AsyncNode](https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/models/gql_relay.py#L77).

**Comment by rapsealk** [comment]
Resolved by #1869
