### ISSUE TITLE
Replace the current etcd3 asyncio wrapper with etcd3aio

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#189]
[etcd3](https://github.com/kragniz/python-etcd3) seems not to be actively maintained for recent months.
Its asyncio backend PR and other bug fix PRs are long-pending.
An alternative implementation is [etcd3aio](https://github.com/hron/etcd3aio) which bases on [grpclib](https://github.com/vmagamedov/grpclib) supporting asyncio natively using h2 and provides a cleaner asyncio-native API and implementation.
Let's try it and replace our etcd3 client backend.

**Comment by achimnol** [comment]
Unfortunately, etcd3aio has not been published to PyPI. 🤔

**Comment by yongkyunlee** [comment]
Using [aetcd3](https://github.com/martyanov/aetcd3) and modifying it to our needs would be a viable option.

**Comment by achimnol** [comment]
We have replaced it with our own etcd client library, [etcetra](https://github.com/lablup/etcetra).
