### ISSUE TITLE
Multiple click on folder shows wrong path on Backend.AI platform

### ISSUE THREAD

**Issue by dumaaan** [lablup/backend.ai#209]
**Describe the bug**
When going to Data & Storage folder, if one clicks on the folder several times while waiting for it to open, it will then add them up on the file path, which is obviously not the actual path.

**To Reproduce**
1. Go to the backend.ai platform. I was using https://cloud.lablup.ai/ domain.
2. Go Data & Storage section. Start a new folder, preferably a large one with many subfolders.
3. While waiting for the folder to load and open, click on it several times.

**Expected behavior**
It will add up the folder you're trying to open to the displayed path.

**Screenshots**
Here, I clicked on both test2017 and val2014 folders while waiting for it to display the file contents. This is the path that the platform displayed to me.

<img width="1697" alt="Screen Shot 2020-08-11 at 4 37 28 PM" src="https://user-images.githubusercontent.com/44192460/89870539-f5c23180-dbf0-11ea-8b39-59d125f880d6.png">

**Client:**
 - OS: MacOS 10.15.5
 - App version: NA
 - Browser version:  Google Chrome, version 84.0.4147.105 (Official Build) (64-bit)
 - Python version: NA
 - NodeJS version: NA

**Server:**
 - OS: NA
   - Output of `uname -a`: NA
 - Backend.AI version: 20.07.8.200723
 - Python version: NA
 - Installation method: cloud.backend.ai service

**Comment by lizable** [comment]
This bug is resolved by https://github.com/lablup/backend.ai-console/pull/718, which is already merged to main branch of GUI console.
Therefore updating cloud console version will fix it automatically.
