### ISSUE TITLE
Add installation to docs

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai#21]
### Description
 * Add installation docs to docs.backend.ai
 * Add markdown support for backend.ai page and readthedocs.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1159751085623729/1159757298948078) by [Unito](https://www.unito.io/learn-more)

**Comment by achimnol** [comment]
Now we have https://docs.backend.ai/en/latest/install/development-setup.html
