### ISSUE TITLE
When installing install-dev.sh in macOS environment, if pyenv is not installed, the installation will not be completed.

### ISSUE THREAD

**Issue by zel0rd** [lablup/backend.ai#211]
**Describe the bug**
- When running scripts/install-dev.sh on macOS, if pyenv and virtualenv are not installed, the installation cannot be completed.

**To Reproduce**
1. [Setting same environment] brew uninstall pyenv / brew uninstall pyenv-virtualenv
2. [execute scripts/install-dev.sh] ./install-dev.sh
3. [See error1] WARNING: Can not proceed with installation. Kindely remove the '/User/./.pyenv' directory first.
4. [Fix error1] brew install pyenv
5. [See error2] [INFO] Creating virtualenv on pyenv... / pyenv: no such command 'virtualenv'
6. [Fix error2] brew install pyenv-virtualenv

**Expected behavior**
If pyenv or pyenv-virtual is not installed, automatically install it using brew.

**Screenshots**
<img width="758" alt="issue_when_not_installed_pyenv" src="https://user-images.githubusercontent.com/28799597/91275467-2c847400-e7bb-11ea-82d3-36fddef78eee.png">
<img width="468" alt="issue_when_not_installed_virtualenv" src="https://user-images.githubusercontent.com/28799597/91275497-36a67280-e7bb-11ea-80f3-f0e2d11ae1c1.png">

**Additional context**
- [ ] I will be revising pyenv and pyenv-virtual within this week so that they can be automatically installed.

**Comment by zel0rd** [comment]
https://github.com/lablup/backend.ai/pull/212

**Comment by achimnol** [comment]
The root problem is here: between your reproduction step 4 and 5, **there is a missing step**.
You must (re-)initialize pyenv for your current shell, by executing `exec "$(pyenv init -)"` or restarting the shell after setting up your shell configuration such as `.bashrc`, `.bash_profile`, `.profile`, etc. [as guided by the pyenv manual](https://github.com/pyenv/pyenv#basic-github-checkout).

**Comment by achimnol** [comment]
The correct fix would be to improve the error messages, so that users can properly "reinstall both pyenv and pyenv-virtualenv" and/or "fix the shell config", not to silenty brew-uninstall as in #212.
Please rewrite #212.

**Comment by achimnol** [comment]
Closing due to long inactivity.
