### ISSUE TITLE
Rewrite the session concurrency tracking mechanism

### ISSUE THREAD

**Issue by fregataa** [lablup/backend.ai#2177]
`concurrency_used` is the number of concurrent sessions belong to a certain user(or a certain access_key).
Currently, it is saved in Redis with `keypair.concurrency_used.{ACCESS_KEY}` key.
It is hard to track all codes update or fetch `concurrency_used` in Backend.AI codebase, so let's refactor it for better debugging and readability.

- Make functions(or APIs) to update/fetch `concurrency_used` in Redis
- Replace all `concurrency_used` code to the new function(or API)

**Comment by achimnol** [comment]
This issue is split into two subissues of #2746: #3156 and #3157.
