### ISSUE TITLE
Warning in WebUI if the pre-open port and the app port of the image overlap

### ISSUE THREAD

**Issue by hoyajigi** [lablup/backend.ai#2189]
### Main idea

If you set pre-open port that is overlapping with the image's app's port (or 2000, 2001), You got Assertion error and session creation fail. So you should prehibit or warn that you cannot use those ports as pre-open port. 

Example of those ports
```
2000, 2001: backend.ai reserved ipython:3000,jupyter:8091,jupyterlab:8090,vscode:8180,tensorboard:6006,mlflow-ui:5000,nniboard:8080
```

**Comment by adrysn** [comment]
Another port which cannot be used as a pre-open port: 2200.
