### ISSUE TITLE
Agent stopped running when kernel image has app labels with duplicate ports

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai#220]
**Describe the bug**
Agent stopped running when kernel image has app labels with duplicate ports

**To Reproduce**

1. In kernel, add app label with same port by visiting 'environment' and choose specific kernel (e.g. nniboard: 8080, which conflicts with Jupyter)
2. Run the kernel
4. See error on agent terminal

**Expected behavior**
Running without stopping agent.

**Screenshots**
<img width="975" alt="image" src="https://user-images.githubusercontent.com/949915/92852787-0ea94700-f42a-11ea-83d2-aa03ff69ef97.png">

**Client:**
 - OS: macOS 10.16
 - App version: 20.09.0
 - Browser version: Chrome 85
 - Python version: 3.8.3

**Server:**
 - OS: macOS 10.15
 - Backend.AI version: 20.09a
 - Python version: 3.8.3
 - Installation method: used scripts/install-dev.sh

**Additional context**

Port conflict should be checked before starting new container.

**Comment by yongkyunlee** [comment]
The agent actually does not stop. If you start another session, which does not have any problem, the session starts running normally.
