### ISSUE TITLE
Add "backend.ai ssh <sessionId>" command

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#228]
Let's add `backend.ai ssh` command to the client SDK, which merges `backend.ai app` and local `ssh` command into one.

**Comment by leksikov** [comment]
Why it is _backend.ai ssh sessionid_ ?
It should be _backend.ai ssh work@localhost -p 9922_

When the session is created the SSH server is not created by default with a fixed port.
To run a ssh server after a session is created, there is a need to explicitly to launch it as in the example: _backend.ai app session_name sshd -b 9922_

**Comment by achimnol** [comment]
Ah, I missed your question here while I paid attention to the PR only...
The rewritten implementation runs `backend.ai app {session_ref} sshd -b ...` as a background process while running the actual `ssh` and `scp` commands as a foreground process.
Since running both commands in separate terminals are cumbersome for users, that's why I've created this issue.

Anyway, now it's done. :)
