### ISSUE TITLE
How to add Hangul font on Container

### ISSUE THREAD

**Issue by blissray** [lablup/backend.ai#231]
When I try to make visualizing plot of matplotlib, I  have to use Korean fonts. How should I add it to a container?

As we all know, sudo commands don't work.

What can I do?

**Comment by achimnol** [comment]
You may download the font in a vfolder to keep it persistent across different sessions and configure matplotlib to use it in the beginning of your program or notebook.

**Comment by blissray** [comment]
Thank you for your answer. I will try it and share the tutorial for other users :).
