### ISSUE TITLE
Add ~/.local/bin to the default PATH in containers

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#250]
Some user-installed executables are placed there.
Let's add it to the default PATH environment variables, even when the image-defined PATH does not include it.

**Comment by 96RadhikaJadhav** [comment]
@achimnol Can you please guide me to the file/path where this needs to be added?

**Comment by achimnol** [comment]
> @achimnol Can you please guide me to the file/path where this needs to be added?

To ensure inclusion of "/home/work/.local/bin" *always*, the PATH variable must be edited after the following code block:
https://github.com/lablup/backend.ai-agent/blob/master/src/ai/backend/kernel/base.py#L126-L141
