### ISSUE TITLE
Add "--override-storage-proxy" option and env-var config to the client SDK

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#252]
Currently the client always uses the storage-proxy address returned by the manager.
However, with specific network configurations (e.g., server-side nodes are inside a NAT router), the clients executed *inside* the server-side node (usually for testing and verifying installation) may not be able to access the public-only address returned by the manager (e.g., unless the router supports a hairpin NAT routing).

There are two ways to solve this:
1. Update the manager to have extra configurations for client-addr-to-proxy-addr mapping.
2. Update the client to be able to override the manager-returned storage-proxy address.

For simplicity, let's do the second option.

The final CLI should look like:
```
backend.ai vfolder --override-storage-proxy=X1=Y1,X2=Y2 upload ...
```
or
```
export BACKEND_OVERRIDE_STORAGE_PROXY="X1=Y1,X2=Y2"
backend.ai vfolder upload ...
```
where Xn are the manager-returned storage-proxy addresses and Yn are the overriden addresses.
Each Xn address must be an IP address or the hostname with optional port number to be returned by the manager. This is used to "match" the manager-returned address.
Each Yn address must at least include the IP address or the hostname and may include the protocol part (e.g., to bypass an SSL termination proxy from the internal network) and the port number to replace.

**Comment by fregataa** [comment]
can Yn be both patterns such as  "http://10.10.10.10:8000" and "10.10.10.10:8000" ?
