### ISSUE TITLE
VFolder lookup API returns "None" string instead of `null`

### ISSUE THREAD

**Issue by rapsealk** [lablup/backend.ai#2548]
### Main idea

**Issue Description:**

When using the VFolder lookup API endpoint `GET /func/folders/{folderName}`, the response behavior for the fields `user` and `group` is inconsistent. According to the API documentation, the response should provide either a string value for `user` or `group`, but not both simultaneously. However, the current behavior of the API returns a "None" string instead of `null` when the respective field is expected to be absent.

![image](https://github.com/user-attachments/assets/85676286-9659-411f-8735-8fe0e98e5cae)

**Steps to Reproduce:**
1. Make a GET request to the endpoint `/func/folders/{folderName}` where `{folderName}` is the name of the folder being queried.
2. Analyze the response for the fields `user` and `group`.
3. Note the presence of a "None" string instead of `null` when the field is expected to be absent.

**Expected Behavior:**
- When the `user` or `group` field is absent from the response, the API should return `null` for that field.

https://github.com/lablup/backend.ai/blob/16f070388eb7cbd1456f44a723989c6cf97b8bd0/src/ai/backend/manager/api/vfolder.py#L696-L697

**Current Behavior:**
- The API returns a "None" string instead of `null` for the `user` or `group` field when it is absent from the response.

https://github.com/lablup/backend.ai/blob/16f070388eb7cbd1456f44a723989c6cf97b8bd0/src/ai/backend/manager/api/vfolder.py#L951-L952

**Impact:**
- This inconsistency in the API response affects applications that rely on accurately detecting the absence of `user` or `group` information. Applications expecting `null` values may misinterpret "None" strings as valid data, leading to incorrect logic and potential errors.

**Workaround:**
- As a workaround, client applications can explicitly check for the presence of "None" strings and treat them as indicators of absent data. However, this workaround introduces additional complexity and potential for errors in application logic.

**Proposed Solution:**
- Modify the API response to adhere strictly to the expected behavior by returning `null` instead of "None" strings for fields `user` and `group` when they are absent from the response.

This issue impacts the reliability and consistency of data retrieval from the VFolder lookup API and should be addressed to ensure correct handling of `null` values in API responses.

**Comment by why-arong** [comment]
I can handle this issue! I will also write and include the test code for vfolder.
