### ISSUE TITLE
Not able to run the manager service

### ISSUE THREAD

**Issue by shivaprasad573** [lablup/backend.ai#268]
Follow the installation script approach [https://docs.backend.ai/en/latest/install/development-setup.html#method-1-automatic-installation](https://docs.backend.ai/en/latest/install/development-setup.html#method-1-automatic-installation) 

Environment:
**OS: Ubuntu 20.04
Python: 3.9.5**

but while running the manager am getting an error.

**Command**
```
python -m ai.backend.manager.server --debug
```

**Error**
``` 
2021-06-16 23:10:56.294 DEBUG ai.backend.manager.config [78986] debug mode enabled.
2021-06-16 23:10:57.851 INFO ai.backend.common.etcd [79049] using etcd cluster from 127.0.0.1:8121 with namespace "local"
2021-06-16 23:10:58.999 INFO ai.backend.common.plugin [79049] loading plugin (group:backendai_error_monitor_v20): intrinsic
2021-06-16 23:10:59.197 ERROR __main__ [79049] Error initializing cleanup_contexts: monitoring_ctx
Traceback (most recent call last):
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 565, in _cleanup_context_wrapper
    async with cctx_instance:
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 437, in monitoring_ctx
    await ectx.init(context={'_root.context': root_ctx})
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/common/src/ai/backend/common/plugin/__init__.py", line 140, in init
    for plugin_name, plugin_entry in scanned_plugins:
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/common/src/ai/backend/common/plugin/__init__.py", line 136, in discover_plugins
    yield entrypoint.name, entrypoint.load()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (PyJWT 2.0.1 (/usr/local/lib/python3.9/dist-packages), Requirement.parse('PyJWT==1.7.1'))
Traceback (most recent call last):
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 632, in server_main
    await runner.setup()
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_runner.py", line 275, in setup
    self._server = await self._make_server()
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_runner.py", line 375, in _make_server
    await self._app.startup()
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_app.py", line 416, in startup
    await self.on_startup.send(self)
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_app.py", line 534, in _on_startup
    await it.__anext__()
StopAsyncIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 671, in server_main_logwrapper
    async with server_main(loop, pidx, _args):
  File "/usr/lib/python3.9/contextlib.py", line 175, in __aenter__
    return await self.gen.__anext__()
RuntimeError: async generator raised StopAsyncIteration
2021-06-16 23:10:59.218 ERROR aiotools.server [79049] Worker 0: Error during context manager initialization
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aiotools/server.py", line 304, in _wrapped_worker
    async with ctx:
  File "/usr/lib/python3.9/contextlib.py", line 177, in __aenter__
    raise RuntimeError("generator didn't yield") from None
RuntimeError: generator didn't yield
2021-06-16 23:10:59.228 ERROR __main__ [79049] Error initializing cleanup_contexts: storage_manager_ctx
Traceback (most recent call last):
  File "/home/ec2-user/projects/backendai/backend-ai/backend.ai-dev/manager/src/ai/backend/manager/server.py", line 566, in _cleanup_context_wrapper
    yield
  File "/usr/lib/python3.9/contextlib.py", line 194, in __aexit__
    raise RuntimeError("generator didn't stop after athrow()")
RuntimeError: generator didn't stop after athrow( 
```

**Comment by achimnol** [comment]
Hmmm... The manager depends on `PyJWT==1.7.1` and the common does not have explicit dependency declaration to it.
How did you install? Are there any additional packages?

**Comment by shivaprasad573** [comment]
First, I tried manual installation but found that few files are missing in the manager by following [](https://docs.backend.ai/en/latest/install/development-setup.html#running-daemons-from-cloned-sources), but not able to find the file **run-with-halfstack.sh** file so switched back to the automated way and installed it.

**Comment by achimnol** [comment]
Those docs are outdated....
Please try this script: https://github.com/lablup/backend.ai/blob/main/scripts/install-dev.sh to fire up a local editable cluster.

**Comment by achimnol** [comment]
And also ensure that your `pyenv` is configured properly and `cd`-ing into a directory with `.python-version` file (set via `pyenv local` command) correctly updates your current virtualenv activation.

**Comment by shivaprasad573** [comment]
Sure, Thank you @achimnol I will give it a try with the new script.

I have installed `pyenv` by following  [https://docs.backend.ai/en/latest/install/install-python-via-pyenv.html](https://docs.backend.ai/en/latest/install/install-python-via-pyenv.html)

**Comment by shivaprasad573** [comment]
I was able to complete the installation process. Thanks, @achimnol but 
After executing the script for the first time it worked fine. But when i run the script again it was stuck and not giving any error or success.

``` 
# backend.ai run python -c "print('Hello World\!')"
```
**1st run**
```
(venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
∙ Session name prefix: pysdk-2dae94bc3c
✔ [0] Session pysdk-2dae94bc3c is ready (domain=default, group=default).
Hello World\!
✔ [0] Execution finished. (exit code = 0)
```

**2nd run**
```
(venv-c6zpblcq-client) root@ubuntu:/home/shiva/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
∙ Session name prefix: pysdk-8772738cc1
```

it was hanged at the Session name line am I missing anything else here?

**Comment by shivaprasad573** [comment]
> I was able to complete the installation process. Thanks, @achimnol but
> After executing the script for the first time it worked fine. But when i run the script again it was stuck and not giving any error or success.
> 
> ```
> # backend.ai run python -c "print('Hello World\!')"
> ```
> 
> **1st run**
> 
> ```
> (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> ∙ Session name prefix: pysdk-2dae94bc3c
> ✔ [0] Session pysdk-2dae94bc3c is ready (domain=default, group=default).
> Hello World\!
> ✔ [0] Execution finished. (exit code = 0)
> ```
> 
> **2nd run**
> 
> ```
> (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> ∙ Session name prefix: pysdk-8772738cc1
> ```
> 
> it was hanged at the Session name line am I missing anything else here?
> 
> and am also not able to access the web UI from the browser tried
> http://localhost:8090 /
> http://0.0.0.0:8090

Just Noticed, While running the agent I see there is a log but the agent started fine.

```
2021-06-17 05:44:46.513 ERROR ai.backend.common.plugin [30544] error during initialization of plugin: intrinsic
Traceback (most recent call last):
  File "/home/user/Projects/backend.ai-dev/common/src/ai/backend/common/plugin/__init__.py", line 146, in init
    await plugin_instance.init(context=context)
  File "/home/user/Projects/backend.ai-dev/manager/src/ai/backend/manager/plugin/error_monitor.py", line 27, in init
    root_ctx: RootContext = context['_root.context']  # type: ignore
TypeError: 'NoneType' object is not subscriptable
```

**Comment by shivaprasad573** [comment]
> > I was able to complete the installation process. Thanks, @achimnol but
> > After executing the script for the first time it worked fine. But when i run the script again it was stuck and not giving any error or success.
> > ```
> > # backend.ai run python -c "print('Hello World\!')"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **1st run**
> > ```
> > (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> > ∙ Session name prefix: pysdk-2dae94bc3c
> > ✔ [0] Session pysdk-2dae94bc3c is ready (domain=default, group=default).
> > Hello World\!
> > ✔ [0] Execution finished. (exit code = 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **2nd run**
> > ```
> > (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> > ∙ Session name prefix: pysdk-8772738cc1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it was hanged at the Session name line am I missing anything else here?
> > and am also not able to access the web UI from the browser tried
> > http://localhost:8090 /
> > http://0.0.0.0:8090
> > Error
> > ```
> > 2021-06-17 06:05:38 ERROR aiohttp.server [34617] Unhandled exception
> > Traceback (most recent call last):
> >   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 485, in start
> >     resp, reset = await task
> >   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 440, in _handle_request
> >     reset = await self.finish_response(request, resp, start_time)
> >   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 591, in finish_response
> >     await prepare_meth(request)
> >   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_fileresponse.py", line 115, in prepare
> >     st = await loop.run_in_executor(None, filepath.stat)
> >   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
> >     result = self.fn(*self.args, **self.kwargs)
> >   File "/usr/lib/python3.9/pathlib.py", line 1222, in stat
> >     return self._accessor.stat(self)
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Projects/backend.ai-dev/webserver/src/ai/backend/web/static/index.html'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the error showing in webserver console
> 
> Just Noticed, While running the agent I see there is a log but the agent started fine.
> 
> ```
> 2021-06-17 05:44:46.513 ERROR ai.backend.common.plugin [30544] error during initialization of plugin: intrinsic
> Traceback (most recent call last):
>   File "/home/user/Projects/backend.ai-dev/common/src/ai/backend/common/plugin/__init__.py", line 146, in init
>     await plugin_instance.init(context=context)
>   File "/home/user/Projects/backend.ai-dev/manager/src/ai/backend/manager/plugin/error_monitor.py", line 27, in init
>     root_ctx: RootContext = context['_root.context']  # type: ignore
> TypeError: 'NoneType' object is not subscriptable
> ```

> I was able to complete the installation process. Thanks, @achimnol but
> After executing the script for the first time it worked fine. But when i run the script again it was stuck and not giving any error or success.
> ```
> # backend.ai run python -c "print('Hello World\!')"
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> **1st run**
> ```
> (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> ∙ Session name prefix: pysdk-2dae94bc3c
> ✔ [0] Session pysdk-2dae94bc3c is ready (domain=default, group=default).
> Hello World\!
> ✔ [0] Execution finished. (exit code = 0)
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> **2nd run**
> ```
> (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> ∙ Session name prefix: pysdk-8772738cc1
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> it was hanged at the Session name line am I missing anything else here?
> and am also not able to access the web UI from the browser tried
> http://localhost:8090 /
> http://0.0.0.0:8090
> Error
> ```
> 2021-06-17 06:05:38 ERROR aiohttp.server [34617] Unhandled exception
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 485, in start
>     resp, reset = await task
>   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 440, in _handle_request
>     reset = await self.finish_response(request, resp, start_time)
>   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 591, in finish_response
>     await prepare_meth(request)
>   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_fileresponse.py", line 115, in prepare
>     st = await loop.run_in_executor(None, filepath.stat)
>   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/lib/python3.9/pathlib.py", line 1222, in stat
>     return self._accessor.stat(self)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Projects/backend.ai-dev/webserver/src/ai/backend/web/static/index.html'
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> This is the error showing in webserver console

Just Noticed, While running the agent I see there is a log but the agent started fine.

```
2021-06-17 05:44:46.513 ERROR ai.backend.common.plugin [30544] error during initialization of plugin: intrinsic
Traceback (most recent call last):
  File "/home/user/Projects/backend.ai-dev/common/src/ai/backend/common/plugin/__init__.py", line 146, in init
    await plugin_instance.init(context=context)
  File "/home/user/Projects/backend.ai-dev/manager/src/ai/backend/manager/plugin/error_monitor.py", line 27, in init
    root_ctx: RootContext = context['_root.context']  # type: ignore
TypeError: 'NoneType' object is not subscriptable
```

and also I noticed continuous messages in the manager service as bellow
```
2021-06-17 06:28:29.242 DEBUG ai.backend.manager.scheduler [60408] schedule(): triggered
2021-06-17 06:28:29.266 DEBUG ai.backend.manager.scheduler [60408] loading scheduler plugin "fifo" from ai.backend.manager.scheduler.fifo
2021-06-17 06:28:29.324 DEBUG ai.backend.manager.scheduler [60408] running scheduler (sgroup:default, pending:9, existing:3)
2021-06-17 06:28:29.330 DEBUG ai.backend.manager.scheduler [60408] schedule(s:c5885ef4-d9fa-451f-995d-38c5704046d7, type:interactive, name:pysdk-7e7aa64c3c, ak:AKIAIOSFODNN7EXAMPLE, cluster_mode:single-node): try-scheduling
2021-06-17 06:28:29.335 DEBUG ai.backend.manager.scheduler [60408] access_key: AKIAIOSFODNN7EXAMPLE (3 / 30)
2021-06-17 06:28:29.351 DEBUG ai.backend.manager.scheduler [60408] keypair:AKIAIOSFODNN7EXAMPLE current-occupancy: {'cpu': Decimal('3'), 'mem': Decimal('1006632960')}
2021-06-17 06:28:29.352 DEBUG ai.backend.manager.scheduler [60408] keypair:AKIAIOSFODNN7EXAMPLE total-allowed: {'cpu': Decimal('Infinity'), 'mem': Decimal('Infinity')}
2021-06-17 06:28:29.369 DEBUG ai.backend.manager.scheduler [60408] group:2de2b969-1d04-48a6-af16-0bc8adb3c831 current-occupancy: {'cpu': Decimal('3'), 'mem': Decimal('1006632960')}
2021-06-17 06:28:29.369 DEBUG ai.backend.manager.scheduler [60408] group:2de2b969-1d04-48a6-af16-0bc8adb3c831 total-allowed: {'cpu': Decimal('Infinity'), 'mem': Decimal('Infinity')}
2021-06-17 06:28:29.380 DEBUG ai.backend.manager.scheduler [60408] domain:default current-occupancy: {'cpu': Decimal('3'), 'mem': Decimal('1006632960')}
2021-06-17 06:28:29.381 DEBUG ai.backend.manager.scheduler [60408] domain:default total-allowed: {'cpu': Decimal('Infinity'), 'mem': Decimal('Infinity')}
2021-06-17 06:28:29.393 DEBUG ai.backend.manager.scheduler [60408] considered scaling groups: ['default']
2021-06-17 06:28:29.403 DEBUG ai.backend.manager.scheduler [60408] schedule(s:c5885ef4-d9fa-451f-995d-38c5704046d7, type:interactive, name:pysdk-7e7aa64c3c, ak:AKIAIOSFODNN7EXAMPLE, cluster_mode:single-node): no-available-instances
2021-06-17 06:28:29.425 DEBUG ai.backend.manager.scheduler [60408] schedule(default): instance not available
2021-06-17 06:28:33.765 DEBUG ai.backend.manager.scheduler [60407] prepare(): preparing 0 session(s)


```

**Comment by shivaprasad573** [comment]
And please let me know if any paid support is available to solve the issues in real time. @achimnol

**Comment by adrysn** [comment]
`instance not available` is displayed in the manager log. Perhaps, the first compute session takes all available resources, such as CPU and/or memory. How about executing `backend.ai admin agents` to list available and occupied resources of every agents? You can check whether your agent has enough resource for another session or not. Note that `admin agents` command only works if you are using admin keypairs.

Also, you can check the currently running compute session by `backend.ai ps`.

If you want to kill one of the running sessions, you can kill `backend.ai rm <session-id>`.

**Comment by achimnol** [comment]
Inside the webserver directory, run `git submodule init` and `git submodule update --recursive`. It's missing in `install-dev.sh` and I'll fix it up.

**Comment by achimnol** [comment]
> And please let me know if any paid support is available to solve the issues in real time. @achimnol

We don't have such a service and our technical support is currently only for paid enterprise customers, while keeping open source discussions and contributions in GitHub.
You may contact our enterprise sales team if your organization/company is interested in using Backend.AI, by sending an inquiry form in the "Contact Us" link at the right bottom corner of https://www.backend.ai website, setting the type field as "Partnership / Sales".

**Comment by achimnol** [comment]
> I was able to complete the installation process. Thanks, @achimnol but
> After executing the script for the first time it worked fine. But when i run the script again it was stuck and not giving any error or success.
> 
> ```
> # backend.ai run python -c "print('Hello World\!')"
> ```
> 
> **1st run**
> 
> ```
> (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> ∙ Session name prefix: pysdk-2dae94bc3c
> ✔ [0] Session pysdk-2dae94bc3c is ready (domain=default, group=default).
> Hello World\!
> ✔ [0] Execution finished. (exit code = 0)
> ```
> 
> **2nd run**
> 
> ```
> (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> ∙ Session name prefix: pysdk-8772738cc1
> ```
> 
> it was hanged at the Session name line am I missing anything else here?
> 

This is an expected behavior when there is no more remaining resources to fit the new session in.
You may use `--max-wait` argument to limit the waiting time and return explicit failure, but the session creation request will still be in the queue and you may cancel it by `backend.ai rm` later.

**Comment by achimnol** [comment]
> Just Noticed, While running the agent I see there is a log but the agent started fine.
> 
> ```
> 2021-06-17 05:44:46.513 ERROR ai.backend.common.plugin [30544] error during initialization of plugin: intrinsic
> Traceback (most recent call last):
>   File "/home/user/Projects/backend.ai-dev/common/src/ai/backend/common/plugin/__init__.py", line 146, in init
>     await plugin_instance.init(context=context)
>   File "/home/user/Projects/backend.ai-dev/manager/src/ai/backend/manager/plugin/error_monitor.py", line 27, in init
>     root_ctx: RootContext = context['_root.context']  # type: ignore
> TypeError: 'NoneType' object is not subscriptable
> ```

It looks like the log trace is from the manager-side error monitoring plugin, but you are saying it happened when running the agent.
That means you might have mixed up installation of the manager and agent in a single virtualenv.
Anyway this might be a bug that happens when trying to log an unhandled exception and I'll look into it.

**Comment by shivaprasad573** [comment]
> > I was able to complete the installation process. Thanks, @achimnol but
> > After executing the script for the first time it worked fine. But when i run the script again it was stuck and not giving any error or success.
> > ```
> > # backend.ai run python -c "print('Hello World\!')"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **1st run**
> > ```
> > (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> > ∙ Session name prefix: pysdk-2dae94bc3c
> > ✔ [0] Session pysdk-2dae94bc3c is ready (domain=default, group=default).
> > Hello World\!
> > ✔ [0] Execution finished. (exit code = 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **2nd run**
> > ```
> > (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> > ∙ Session name prefix: pysdk-8772738cc1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it was hanged at the Session name line am I missing anything else here?
> 
> This is an expected behavior when there is no more remaining resources to fit the new session in.
> You may use `--max-wait` argument to limit the client-side waiting time and return explicit failure, but the session creation request will still be in the queue and you may cancel it by `backend.ai rm` later, as @adrysn has described above.


Thanks for the reply @achimnol.
My VM has **6GB RAM** and **2 CORES** assigned to it and as mentioned before am using **Ubuntu-20.04** OS

Please can you also provide minimum **System Requirements** for this project to run without issues

And first execution is completed right. still, it holds the CPU resources?

**Comment by achimnol** [comment]
> > > **1st run**
> > > ```
> > > (venv-c6zpblcq-client) root@ubuntu:/home/user/Projects/backend.ai-dev/client-py# backend.ai run python -c "print('Hello World\!')"
> > > ∙ Session name prefix: pysdk-2dae94bc3c
> > > ✔ [0] Session pysdk-2dae94bc3c is ready (domain=default, group=default).
> > > Hello World\!
> > > ✔ [0] Execution finished. (exit code = 0)
> > > ```
> Thanks for the reply @achimnol.
> My VM has **6GB RAM** and **2 CORES** assigned to it and as mentioned before am using **Ubuntu-20.04** OS
> 
> Please can you also provide minimum **System Requirements** for this project to run without issues
> 

Since you have not specified the resource requirements (refer the help message of `run` command and `-r`, `--resource` arguments), it will use the minimum resource requirement of the given image.
In this case, [the "python" alias points to "cr.backend.ai/stable/python:3.8-ubuntu18.04"](https://github.com/lablup/backend.ai/blob/7b9459a5107d030237d7384560a39ae51f67d839/scripts/install-dev.sh#L641) and [it requires 1 CPU core at least](https://github.com/lablup/backend.ai-kernels/blob/master/python/Dockerfile.3.8-ubuntu18.04#L64).
Sicne your setup has 2 CPU cores and [the agent by default reserves 1 CPU core for its operation](https://github.com/lablup/backend.ai-agent/blob/b49de6f58d5c3c26c8eb456abb04c1f4643e0917/config/sample.toml), you can run only one session and that's why it looks stuck on the second execution.

> And first execution is completed right. still, it holds the CPU resources?

Yes, it's still running unless you terminate the session.
Just like Docker CLI, you may pass `--rm` to automatically terminate the session when the code execution finishes.
There is another command, `start`, to just start a session without executing any code and this is the preferred way when you're going to use the in-container applications via `backend.ai app` command.

You may check the capacity and occupation of agents using `backend.ai admin agents` command.

**Comment by shivaprasad573** [comment]
Now I have stopped all the sessions, using `backend.ai rm <sessionid>`.
Now I have installed web modules also using `git submodule init ` and `git submodule update --recursive` and am able to open and login to WebUI. Thanks for the help @achimnol 

After executing the `backend.ai run python -c "print('Hello World\!')"` it opened a session but it is not closed.

1. If I have to run another python script how can I do that?
2. I also tried to create an `Authentication` token to use API's but I did not find the relevant docs for it. Please can you help me to get the token?
3. Please can you give me instructions to install run the java code snippets using API's

**Comment by achimnol** [comment]
1. See https://client-py.docs.backend.ai/en/latest/cli/sessions.html, though some parts may be adjusted to the latest state of codes.
2. Refer the source code of https://github.com/lablup/backend.ai-client-py, or use it to automate your scripts.
3. To run Java codes, you should install (or build) the Java environment image. [You may start from here](https://github.com/lablup/backend.ai-kernels/tree/master/java), but we are not currently maintaining the Java image actively -- please do it by yourself. Build an image [following the instructions here](https://docs.backend.ai/en/latest/dev/adding-kernels.html) and [referring existing images](https://github.com/lablup/backend.ai-kernels), push it to a registry, configure the registry information to the manager's etcd ([example](https://github.com/lablup/backend.ai/blob/7b9459a5107d030237d7384560a39ae51f67d839/scripts/install-dev.sh#L637-L639)), run `backend.ai admin rescan-images`, and then you will be able to start a session with that image.

**Comment by shivaprasad573** [comment]
Sure @achimnol 
I looked at [https://github.com/lablup/backend.ai-client-py](https://github.com/lablup/backend.ai-client-py) but I found that again login using the console/terminal only right.

My use-case is I want to run the python code using a `cURL` request. to do that backend APIs are required right. So that documentation along with Auth token generation.

**Comment by achimnol** [comment]
Check out https://github.com/lablup/backend.ai-client-py/blob/main/src/ai/backend/client/auth.py
We have no examples doing it with cURL and it seems to be difficult because you need to inspect the HTTP headers to generate the signature using custom codes.

**Comment by shivaprasad573** [comment]
> Check out https://github.com/lablup/backend.ai-client-py/blob/main/src/ai/backend/client/auth.py
> We have no examples doing it with cURL and it seems to be difficult because you need to inspect the HTTP headers to generate the signature using custom codes.
> I cannot make such specific usecase examples for you. Since your use-case could be developed from what's publicly available on our GitHub, so please check out the source codes and adapt them to your cases.

So, Can I understand like we can not run the python/java scripts using API tools like Postman/Restlet, etc?

**Comment by achimnol** [comment]
There is a way to use `backend.ai proxy` command which provides **insecure** but transparent API proxy against the manager with pre-configured credentials for the client SDK. For local setups, you could try this one.

**Comment by achimnol** [comment]
If you need a more serious client support, you could just read the client SDK source code and rewrite as you need (e.g., in different language, etc.).

**Comment by shivaprasad573** [comment]
> SDK

Sure, please can you provide me a reference link to achieve this. I will try to use that. And the APIs that I need to invoke with headers

**Comment by shivaprasad573** [comment]
> There is a way to use `backend.ai proxy` command which provides **insecure** but transparent API proxy against the manager with pre-configured credentials for the client SDK. For local setups, you could try this one. Your clients do not need to attach any authentication headers or cookies to make requests via this proxy.

Sure, please can you provide me a reference link to achieve this. I will try to use that. And the APIs that I need to invoke with headers

**Comment by achimnol** [comment]
For your case, all required materials are available open-source, and just utilize them. Sorry for some outdated/incomplete documentation, but since this is an open source, I cannot babysit you infinitely with questions that can be resolvable with publicly available source codes. Please read the codes.

**Comment by achimnol** [comment]
Closing as there seems to be no more activities.
Please feel free to reopen or create another issue for more specific questions.
