### ISSUE TITLE
Extend accelerator plugin architecture to allow container user to join extra Linux groups

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai#2850]
### Main idea

There are cases where accelerator driver requires Linux user to join on specific groups (e.g. [ROCm](https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/prerequisites.html)). To support such cases we can think of extending current accelerator plugin architecture to expose extra set of gids which container user (`work` user) will be joined at. 

### Anything else?

This issue can work as a keystone job of #2592, as the implementation of this feature will allow way to make container user join extra groups other than default GID and `44` (`shadow`).

**Comment by achimnol** [comment]
We could add a new environment variable containing the list of additional GIDs to be passed to `su-exec` via `entrypoint.sh` like `LOCAL_USER_ID` and `LOCAL_GROUP_ID`.
