### ISSUE TITLE
Let's make a new markdown file to save a install information

### ISSUE THREAD

**Issue by mindgitrwx** [lablup/backend.ai#290]
**Is your feature request related to a problem? Please describe.**
At the very beginning of the Backend.ai installation, developers use this script.
- [install-dev.sh] https://github.com/lablup/backend.ai/blob/main/scripts/install-dev.sh

This prints out critical notes for development like ID, password, keypair, environment ID at the end of the installation. 
But we always copy this information manually in the terminal.

**Describe the solution you'd like**
Automating extract this information to another file - like 'INSTALL_INFO.md'

**Describe alternatives you've considered**
I wonder markdown file format is the best option. If there is a better way, please let me know.

**Additional context**
![Selection_254](https://user-images.githubusercontent.com/37054916/133930330-39b0c365-fcb8-47ad-aece-b6a26f17f82e.png)

**Comment by lizable** [comment]
@mindgitrwx How about providing other file extensions(.txt) for convenience sake?
