### ISSUE TITLE
Allow shell evaluation and accessing env-vars in the start command of model-definition.yaml

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai#2909]
### Main idea

As for now, Backend.AI only supports passing command line arguments on model definition's "command" directive. We can think of expanding the feature by switching under-the-hood implementation at the kernel runner to treat whole arguments passed as a shell command.

**Comment by achimnol** [comment]
If you want to join the string pieces when the startup command is given as a list to pass the joined results to a shell, use [`shlex.join()`](https://docs.python.org/3/library/shlex.html#shlex.join).
