### ISSUE TITLE
'backend.ai app' commands do not match with session name properly

### ISSUE THREAD

**Issue by mindgitrwx** [lablup/backend.ai#297]
**Describe the bug**
`backend.ai app` commands do not match with session name properly

**To Reproduce**
1. `cd ~/backend.ai-dev/client-py`
2. `backend.ai ps -f name,image` ()
![image](https://user-images.githubusercontent.com/37054916/136572358-08ff4ae0-c81c-43da-b010-0a63768e5ab4.png)

(I made two different sessions - everything is the same except for name) 
3. `backend.ai app -b '127.0.0.1:8099' jonghyeonJulia jupyter`

4 This generates this error.
```
✘ BackendAPIError: 404 Not Found
  Too many sessions matched.
  Candidates (up to 10 recent entries):
  - ad7d1301-dd4f-4989-8746-537fb118923a (jonghyeonJulia2, RUNNING)
  - b82ee4dd-165a-4a9b-a98a-b74a50763a74 (jonghyeonJulia, RUNNING)

```

**Expected behavior**

This is proper behavior.
```
  backend.ai app -b '127.0.0.1:8099' jonghyeonJulia jupyter
∙ A local proxy to the application "jupyter" provided by the session "jonghyeonJulia" is available at:
  tcp://127.0.0.1:8099

```

**Server:**
 - OS:  Ubuntu 18.04
   - Output of `uname -a`: [Linux mindgitrwx 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux]
 - Backend.AI version: [backend.ai, version 21.09.0a2]
 - Python version: [ 3.9.5]
 - Installation method: [ used scripts/install-dev.sh]

**Additional context**
`backend.ai app -b '127.0.0.1:8099' jonghyeonJulia2 jupyter` works well.

**Comment by achimnol** [comment]
This is a good catch! The current API handler just matches the prefix and returns an error when there are multiple matching result. We need to update the condition part of database query to check exact matching as well.
