### ISSUE TITLE
Update docs for session command options

### ISSUE THREAD

**Issue by mindgitrwx** [lablup/backend.ai#298]
**Describe the bug**
![image](https://user-images.githubusercontent.com/37054916/136580278-f9cb0a46-929d-4725-8c8e-33a64d755d06.png)

1. `backend.ai admin session` does not have `--format`
2. With backend.ai ps, 

**To Reproduce**
https://client-py.docs.backend.ai/ko/latest/cli/sessions.html#listing-sessions

**Expected behavior**
1. `backend.ai admin session` does not have `--format`
2. I guess the command changed as `backend.ai ps -f` 
3. But `id, last_updated, task_id, used_memory, cpu_using option` options are also deprecated.
`✘ There is no such format option: cpu_using`

**Server:**
 - OS:  Ubuntu 18.04
   - Output of `uname -a`: [Linux mindgitrwx 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux]
 - Backend.AI version: [backend.ai, version 21.09.0a2]
 - Python version: [ 3.9.5]
 - Installation method: [ used scripts/install-dev.sh]

**Comment by Yaminyam** [comment]
The --filter option is an option that exists in the admin session list.
However, the list is missing from the example command, causing confusion.

**Comment by Yaminyam** [comment]
This issue covers editing docs, and filters that handle multiple sessions are covered in issue #1287.
