### ISSUE TITLE
Add command line logging option 

### ISSUE THREAD

**Issue by mindgitrwx** [lablup/backend.ai#299]
**Is your feature request related to a problem? Please describe.**
Current backend.ai modules can be executed with the 'debug' option. 
For example, `python -m ai.backend.manager.server --debug`
But other logging options like 'notset', 'info', 'warning', 'error', 'critical' options are must be setted on .toml files.

I want to use all logging options directly on the command line.

**Describe the solution you'd like**

These pictures are brief implementations after modified code.
 
`python -m ai.backend.manager.server --debug`

![Selection_259](https://user-images.githubusercontent.com/37054916/136644146-b9f38e1f-c9e7-4592-ba57-33fcd013123f.png)

`python -m ai.backend.manager.server --info`

![Selection_260](https://user-images.githubusercontent.com/37054916/136644144-593a0831-905e-4aed-8eb3-ecf446e04ed1.png)

`python -m ai.backend.manager.server --warning`

![Selection_261](https://user-images.githubusercontent.com/37054916/136644134-a028ffce-db9a-4b82-bdb9-e254e728cf8e.png)

**Comment by achimnol** [comment]
Maybe it would be better to have a general scheme to map the CLI options with TOML options for CLI-side override.
