### ISSUE TITLE
Enhance testing and CI

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#3]
We are using pytest and Travis CI for testing and continuous integration.
However, we still have limited code coverage and the test cases are lagging behind due to eager feature additions and code refactoring.

**The goal:** raise the code coverage as much as possible, by adding or modifying test cases.

**The benefits:**
 * You will get familiar with unit testing on Python. We hope that you would feel natural to `mkdir tests` from the very beginning of all your future Python projects afterwards.
 * You will get guidances on how to write "good" tests as well as realistic tests with various techniques including mocks and virtual server/clients.

**The challenges:**
 * You need to understand how the code works and what is the intended behavior. The code may have bugs (of course) and you might find surprising mistakes!
 * Our codebase is changing fast, as we implement new features and refactor them at a fast pace. Modifying existing test cases may require some time-consuming repetitive work. Your editor/regex/scripting/typing skills would shine here.
 * The internal functions and APIs are not well-documented. Some small functions are trivial but others are not. You need a good communication skill to ask frequently and discuss with us.

**Coverage:**
 * You may choose all or subset of Sorna subprojects to work with.
 * sorna-media project also has Javascript codes; it will be also interesting if you want to play with testing on Javascript.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1159751085623729/1159757173408490) by [Unito](https://www.unito.io/learn-more)

**Comment by Myeongjoon** [comment]
Hello. 
I'am mentee at contributon 2019. 
This issue seems outdated.
Is the issue still valid?

**Comment by achimnol** [comment]
Integration tests: #144 
Unit tests: will be rewritten gradually.
