### ISSUE TITLE
RuntimeError occurs in mac M1

### ISSUE THREAD

**Issue by youngjun0627** [lablup/backend.ai#314]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.
After installing backend.ai-dev 21.09 version, I execute sample code(`backend.ai run --c 'print("hello")' python`). But, the runtime error "Cancelled waiting of container startup due to initialization failure or agent shutdown" in agent occurs. For finding out the reason, I print [the error](https://github.com/lablup/backend.ai-agent/blob/fe890ce6f4e79d12f7f1eb6bca678829c07c06c6/src/ai/backend/agent/agent.py#L1472) and the error is "socket operation on non-socket". I don't know this problem is related on socket or docker in mac m1. Also, this problem occurred not only to me but also to Yujung. The [link](https://github.com/lablup/contribution-academy-2021/discussions/111) is discussion written by Yujung.
The Following image shows the problem.
![image](https://user-images.githubusercontent.com/57058726/143840430-fe7e7b98-ebcc-49f0-8a78-490e4a1e9bc3.png)

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. Install backend.ai dev, 21.09 version
2. Execute any code(ex: `backend.ai run -c 'print("hello")' python`)
3. See error

**Environment:**
 - OS: macOS Big sur 11.5.1
 - Python version: [e.g. 3.9.8] 
 - installation method : used scripts/install-dev.txt

**Comment by lizable** [comment]
@youngjun0627
Now we finished our test about `arm64(linux/aarch64)` based image, and pushed the image into the public.
Please follow the guide below:
1. Rescan images
execute command below: 
   `backend.ai mgr etcd rescan-images cr.backend.ai`

2. Inspect image
execute command below:
   `backend.ai mgr etcd inspect-image "cr.backend.ai/stable/python:3.8-ubuntu20.04-arm64"`
   
3. Dealias default image (`cr.backend.ai/stable/python:3.8-ubuntu20.04`)
execute command below:
`backend.ai mgr etcd dealias python`

4. Alias new image (`cr.backend.ai/stable/python:3.8-ubuntu20.04-arm64`)
execute command below:
`backend.ai mgr etcd alias python "cr.backend.ai/stable/python:3.8-ubuntu20.04-arm64"`

5. Execute example code
   > CAUTION🚨 : It might take a while at the first code execution, since the image will be in pulling status.
   execute command below:
   `backend.ai run -c 'print("hello")' python`

6. See the result.
![image](https://user-images.githubusercontent.com/46954439/146157410-e867ea18-7d85-40df-9d7e-4009b804e7d8.png)

**Comment by youngjun0627** [comment]
I confirmed that it was operating normally. Thank you:)

**Comment by achimnol** [comment]
Closing!
