### ISSUE TITLE
Add mutation query for agents table to update scaling_group column

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#317]
Recently, the mutation GQL for `agents` is merged by https://github.com/lablup/backend.ai-manager/pull/500. As a follow-up of the PR, let's add the feature to update the `scaling_group` field by the same mutation. This will make admins easy to change the scaling group on their own.

Related: https://github.com/lablup/backend.ai-manager/pull/500

**Comment by achimnol** [comment]
The scaling group column is updated when a manager instance receives agent heartbeat, and the scaling group of an agent is configured via its TOML to implement automatic joining to a cluster.
I agree with the motivation of admin-configurable scaling groups via APIs, but we need to implement it differently, maybe also updating the agent's configuration (via RPC?) in addition to the database update.

**Comment by achimnol** [comment]
https://github.com/toml-lang/toml/issues/284
There is a feature request, but there seems to be no practical implementation supporting it. 😞

**Comment by achimnol** [comment]
The agent PR needs a minor fix.
