### ISSUE TITLE
Emacs package for running backend.ai (emacs-backend.ai-runner)

### ISSUE THREAD

**Issue by mindgitrwx** [lablup/backend.ai#324]
**Is your feature request related to a problem? Please describe.**
It's not about the specific problem of backend.ai. Just a suggestion. 
This idea came from this emacs docker package that wraps docker's command-line interface
https://github.com/Silex/docker.el

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

##### TLDR: Emacs package - Backend.ai command line wrapper 
I want to use backend.ai CLI feature in emacs.

The idea comes from emacs docker package. This gif shows a simple usage . There are many more features listed at the github link of docker.el

As you can see, docker.el is just an wrapper of the command-line interface of docker.
![emacs_docker_runner](https://user-images.githubusercontent.com/37054916/146136434-db3ea333-0117-4604-b21c-007fd5bf7498.gif)

Analyzing the structure of docker.el, I thought about how it could be applied to backend.ai.
There are some thoughts while I tried to implement a simple prototype of emacs-backend.ai-runner 

1. It must be implemented on isolated repository
2. Simply wrapping a backend.ai command line interface using elisp is not a challenging as it seems.
3. Implementing fully-fledged backend.ai feature is not an aim for this feature request. 

![emacs-backend ai-runner](https://user-images.githubusercontent.com/37054916/146134329-65c60421-0210-4f00-9373-b89f800b211a.gif)

**Describe alternatives you've considered**

We can also make this type of plugin on vim.
There is a similar repository. 
https://github.com/kkvh/vim-docker-tools

**Comment by achimnol** [comment]
Wow! 👀

**Comment by achimnol** [comment]
This issue has no follow-up for more than 6 months. Closing as stale.
Feel free to if there are anyone willing to contribute this.
