### ISSUE TITLE
Update Backport GitHub actions

### ISSUE THREAD

**Issue by HyeockJinKim** [lablup/backend.ai#3335]
## Motivation  

[Why is this Task important? Explain the context and reasons for this task.]  

- Backport PRs are currently not being registered as pull requests in Jira, causing tracking issues.

## Objective  

[Clearly state the purpose or goal of this task.]  

- Ensure that backport PRs are also registered as pull requests in Jira.

## Details  

[Outline the specific steps or changes needed to complete this task.]  

1. Discussion is needed on how to register backport PRs as pull requests in Jira.
   1. **Option 1**: Always include the Jira issue key in the PR title (e.g., feat(BA-2): Add...).
      1. This would require modifying the PR title checker.
   1. **Option 2**: Copy the content of the original PR into the backport PR.
      1. This would require ensuring that content is passed during the backport creation process.

## Impact  

[Describe how this task may indirectly influence other services, if at all.]  

- This task will enable Jira to track backport PRs effectively.

**Comment by achimnol** [comment]
Done via #3338.
