### ISSUE TITLE
webserver's Jinja2 package dependency error

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai#338]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.

When I reinstall backend.ai webserver package, I found that message.
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
backend-ai-manager 22.3.0.dev0 requires Jinja2~=3.0.1, but you have jinja2 2.11.3 which is incompatible.
```
Current dev's backend.ai webserver package requires Jinja2 3.0.1 version, not a jinja2 2.11.3 version.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. move to backend.ai webserver directory.
2. enter `pip install -U pip setuptools && pip install -U -r requirements/dev.txt && pip install -U -e ../common`
3. See error
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
backend-ai-manager 22.3.0.dev0 requires Jinja2~=3.0.1, but you have jinja2 2.11.3 which is incompatible.
```

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.

clearly install backend.ai.web.server packages

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.

가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.
<img width="1258" alt="스크린샷 2022-01-04 오후 5 38 29" src="https://user-images.githubusercontent.com/20002/148031774-107997ef-82c4-44fa-a194-cf849253100f.png">

**Server:**
 - OS: macOS 11.1.6
   - Output of `uname -a`: 
   - `Darwin jihyunkcBookPro.office.lablup 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64`
 - Backend.AI version: 22.3.0.dev0
 - Python version: 3.9.9
 - Installation method:   used scripts/install-dev.sh

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

**Comment by achimnol** [comment]
It seems that you have tried to install both `backend.ai-webserver` and `backend.ai-manager` in a single virtual environment, because you are reporting dependency issue about webserver but your screenshot says that the manager is requiring different version of Jinja2.
Anyway, it is good to upgrade Jinja2 package in webserver to a latest one, but the reason of your report is an unsupported case. All Backend.AI server-side components (except `client-py` and `common`) are assuming separate, individual virtualenvs.
