### ISSUE TITLE
Limit session types per scaling group

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#343]
Let's add a scaling-group config option to limit specific session types to be launched in the scaling group.

**Comment by lizable** [comment]
Related issue: [webui#1190](https://github.com/lablup/backend.ai-webui/issues/1190)

**Comment by achimnol** [comment]
NOTICE: When backporting this to an enterprise release, you must backport **both lablup/backend.ai-manager#523 and lablup/backend.ai-manager#542.** @adrysn @xyloon
