### ISSUE TITLE
Unified CLI

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#35]
Currently we have three types of CLI:

* Client CLI (provided by `ai.backend.client.cli`) : `backend.ai ...`
* Manager CLI (provided by `ai.backend.manager.cli`): `python -m ai.backend.manager.cli ...`
* Agent CLI (provided by random modules under `ai.backend.agent`): e..g, `python -m ai.backend.agent.kernel build-krunner-env ...`

Let's unify them under the single `backend.ai` command using [Click](https://click.palletsprojects.com)'s lazy module loading.

Example if manager & agent & client are installed at the same host:
```console
(venv-client) $ backend.ai run --rm python:3.6-ubunt18.04 main.py
(venv-client) $ backend.ai ps
(venv-manager) $ backend.ai mgr etcd get --prefix config
(venv-manager) $ backend.ai mgr start-server
(venv-agent) $ backend.ai ag start-server
(venv-agent) $ backend.ai ag start-watcher
```
where `ag` is an alias to `agent` and `mgr` is an alias to `manager`.
For backward-compatibility and usability, the client commands take the root while manager and agents commands are loaded under subcommands.

NOTE: If we separate virtualenvs for manager, agent, and client, each virtualenv will have its own meta-cli package: so inside the manager's venv, we can only run `backend.ai mgr` subcommands, for example.
At least, we could give the unified experience to access any CLI-based functions.

To do this:
* [x] Create a meta-cli pacakge [`backend.ai-cli`](https://github.com/lablup/backend.ai-cli)
* [x] Add `backend.ai-cli` to dependencies of the manager, agent, and client.
* [x] Let the meta-cli package provide the main entry point "backend.ai".
* [x] Modify all existing CLI codes to work with the meta-cli package.

**Comment by miraliahmadli** [comment]
Opened pull requests in agent, manager, and client.py repositories:

- [https://github.com/lablup/backend.ai-client-py/pull/83](client)

- [https://github.com/lablup/backend.ai-agent/pull/165#35](agent)

- [https://github.com/lablup/backend.ai-manager/pull/218](manager)

And committed changes to cli repository
