### ISSUE TITLE
Let's provide msg when Cancelled error raised during Session creation

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai#364]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.
If kernel creation has failed due to lack of corresponding kernel image, It will raise CancelledError.
For now, we don't have a descriptive error msg about this situation.

> ⚠️ NOTE: You may need an access to see agent server to see the error logs.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. Access to webserver URL.
2. Click on 'START' button in Summary or Sessions page
3. Select Any image that doesn't match with machine architecture of the agent. (e.g. If Agent machine uses x86, choose ARM64 image)
4. Create the session.
5. See the error in agent server.

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.
If session creation failed due to mismatch of kernel image architecture and agent machine itself, it should be described in status detail message.

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.
![Screen Shot 2022-02-09 at 3 25 19 PM](https://user-images.githubusercontent.com/46954439/153144464-b149ed0a-887e-4cb2-87d4-4fdfd37cc435.png)

**Client:**
 - OS: macOS Big Sur 11.6 [e.g. macOS 10.14, Windows 10 (1903)]
 - App version: [e.g. 19.08.3] (if you are using a GUI client app)
 - Browser version: [e.g. Chrome 76, Safari, Edge] (if you are using a GUI web console)
 - Python version: [e.g. 3.7.4] (if you are using the Python SDK)
 - NodeJS version: [e.g. 12.0] (if you are using the Javascript SDK)

**Server:**
 - OS: macOS Big Sur 11.6 [e.g. Ubuntu 18.04, CentOS 7.6, macOS 10.14]
 - Output of `uname -a`: [e.g. `Linux node01 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`] Darwin ****.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64
 - Backend.AI version: 22.03.0.dev0 [e.g. 19.09.0]
 - Python version: 3.9.9 [e.g. 3.6.8]
 - Installation method: scripts/install-dev.sh [e.g. on-premise, using cloud.backend.ai service, used scripts/install-dev.sh]

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

**Comment by fregataa** [comment]
Catching `CancelledError` by matching value pattern to `BaseException` was handled in #1771
Filtering out agents by the requested image when scheduling a session was handled in [#541 pr in archived manager repo](https://github.com/lablup/backend.ai-manager/pull/541)
