### ISSUE TITLE
Automate API docs generation

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#371]
Let's automate the generation of API documentation from the codebase.

Goals:
 * Generate API docs from the code.
 * Make the process of writing/updating API docs a part of the code review.

How:
 * Make it machine-processable by using standard intermediate representations such as Swagger.
   - We may need to write some specialized codes to handle edge cases specific to our codes.
   - Even in such cases, abstract it as much as possible by naming the patterns.
   - Depending on the implementation, either parsing the code statically or importing the modules are okay.
 * Generate the web-browsable API docs from the IR.
 * Use GitHub Actions or Netlify's auto-deploy pipeline. (If possible, let the auto-generated API docs of each PR accessible via a unique URL, just like our technical blog.)

**Comment by Yaminyam** [comment]
https://github.com/lablup/backend.ai/pull/1347, https://github.com/lablup/backend.ai/pull/1691, https://github.com/lablup/backend.ai/pull/1671
Resolved with 3 PRs.
