### ISSUE TITLE
Support to docker aarch64 image for linux arm versions on install-dev.sh

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai#379]
**Is your feature request related to a problem? Please describe.**
기능 요청이 특정 문제에 연관된 것이라면 여기에 그 문제를 설명해주세요.

Support to docker aarch64 image for linux arm versions on install-dev.sh
on `install-dev.sh`, It only support two platforms: `x86_64` and `arm`.
Check the code
https://github.com/lablup/backend.ai/blob/main/scripts/install-dev.sh#L785

However, many Linux distributions(such as openSUSE, Ubuntu) on ARM64, IT shows `aarch64`

example) Ubuntu 20.04 LTS ARM version
```
dhsung@ubuntu-dhsung:~$ uname -a
Linux ubuntu-dhsung 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:44:51 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
dhsung@ubuntu-dhsung:~$ uname -m
aarch64
dhsung@ubuntu-dhsung:~$ uname -p
aarch64
dhsung@ubuntu-dhsung:~$ 
```
![image](https://user-images.githubusercontent.com/20002/154646733-01fd89ab-dc8d-4fde-be13-dd5b87a91969.png)

example) Ubuntu 20.10 ARM version
```
dhsung@dhsung-ubuntu:~$ uname -a
Linux dhsung-ubuntu 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:44:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
dhsung@dhsung-ubuntu:~$ uname -m
aarch64
dhsung@dhsung-ubuntu:~$ uname -p
aarch64
dhsung@dhsung-ubuntu:~$ 
```
<img width="944" alt="image" src="https://user-images.githubusercontent.com/20002/154646990-4fa15ea4-9056-4db0-bf13-acd43f513c98.png">

example) Arch ARM version

```
# uname -p
unknown
# uname -a
Linux alarm 5.5.7-1-ARCH #1 SMP Mon Mar 2 19:16:54 MST 2020 aarch GNU/Linux
# uname -m
aarch64
```
<img width="576" alt="image" src="https://user-images.githubusercontent.com/20002/154681678-a43baa24-fd31-4c0f-a9ab-2027955048ff.png">

example) openSUSE ARM version 
```
> uname -a
Linux localhost.localdomain 5.16.6-1-default #1 SMP Thu Feb 3 05:26:48 UTC 2022 (1af4009) aarch64 aarch64 aarch64 GNU/Linux
> uname -m
aarch64
> uname -p
aarch64
```
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/20002/154692583-78cda423-600a-45f8-b8f3-bb4c5631041f.png">

**Describe the solution you'd like**
어떤 기능이 있으면 좋겠는지 자세히 설명해주세요.

For Linux ARM distribution, use `aarch64` when enter the `uname -m`
 

**Describe alternatives you've considered**
혹시 다른 대안들을 생각해본 적이 있다면 함께 적어주세요.

**Additional context**
기능 요청에 대해 보다 잘 이해할 수 있는 다른 맥락을 기술해주세요.

**Comment by achimnol** [comment]
macOS says "arm64" and most Linux distros say "aarch64".
We need to normalize the architecture names just [like we did in the agent](https://github.com/lablup/backend.ai-agent/blob/2b232574b90bd11ada49aa2b9b272caa9e8e512c/src/ai/backend/agent/utils.py#L80).

**Comment by achimnol** [comment]
Now we have `cr.backend.ai/multiarch` and working multi-arch image with support in `install-dev.sh`.
