### ISSUE TITLE
[문의] 멀티노드 클러스터 세션 생성을 위한 agent 설치

### ISSUE THREAD

**Issue by meeshel78** [lablup/backend.ai#394]
**Is your feature request related to a problem? Please describe.**

meta repository의 install-dev.sh를 사용하여 manager, agent, storage-proxy, webserver 를 설치하였습니다.
webui를 사용하고 있으며, 멀티노드 클러스터 세션 생성을 하려고 하는데 이를 위한 agent 설치는 어떻게 해야 하는 건지요?
현재는 단일 agent 만 동작하는 것으로 보여집니다.

**Comment by achimnol** [comment]
install-dev.sh는 단일 노드의 개발환경 설치를 자동화하는 스크립트입니다.
새로운 노드를 추가하기 위해서는 로컬네트워크로 연결된 별도의 PC 또는 서버에 추가로 agent를 설치하시거나 혹은 VM으로 agent를 설치하셔야 하며, 이때 agent.toml 파일은 직접 설정하셔야 합니다. (install-dev.sh로 설치된 내용을 참고하여 IP 주소 등을 맞춰주시면 됩니다.) 그리고 스토리지 폴더 연계 기능을 사용하기 위해서는 NFS, SMB 등의 네트워크 파일 시스템을 사용하여 storage-proxy의 volume 마운트 탑재 위치를 각 agent 간에 동일하도록 맞춰주셔야 합니다.
