### ISSUE TITLE
Add a lock lifetime (TTL) to `FileLock` as a watchdog

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#413]
To guarantee liveness of distributed locks, we need to ensure release of the locks even when the lock holder gets hang or abruptly killed.
We have implemented auto-release of locks with `EtcdLock` with explict leases, but `FileLock` currently does not have such mechanism and just relies on the kernel's automatic file descriptor cleanup upon (abrupt) shutdown.
This issue is separated from the original lablup/backend.ai-common#136 because it has relatively lower priority as file locks are used for non-HA setup.

* [ ] **common:** Add a watchdog timer and auto-release the lock after the given timeout.
* [ ] **manager:** Update the lock factory in `manager.server` to pass the lifetime hint to `FileLock`.

**Comment by rapsealk** [comment]
Is this kind of replacing `Lock` based things to `Lease` based?
