### ISSUE TITLE
Potential `UnboundLocalError` found in `backend.ai-manager`

### ISSUE THREAD

**Issue by rapsealk** [lablup/backend.ai#421]
**Describe the bug**
With the whole project set to version `21.09`, I ran a backend.ai session using code below:
```zsh
% python -m ai.backend.manager.server --debug
% python -m ai.backend.web.server
% cd /Users/rapsealk/Desktop/git/backend.ai/backend.ai-dev/client-py
% source env-local-admin-api.sh
% backend.ai run python -c "print('Hello World\!')"
```
Then the code raised an `UnboudLocalError` at **L802** from the code below:
https://github.com/lablup/backend.ai-manager/blob/4f5f82ee76b569414af9b66459287098146fc57f/src/ai/backend/manager/config.py#L790-L803
```zsh
UnboundLocalError: local variable 'min_value' referenced before assignment
```

**To Reproduce**
1. Clone and install `backend.ai`.
```zsh
% git clone https://github.com/lablup/backend.ai.git --depth 1 -b 21.09
% cd backend.ai
backend.ai % ./script/install-dev.sh --server-branch 21.09 --client-branch 21.09
```
2. Run `backend.ai-manager` and `backend.ai-webserver` servers.
```zsh
backend.ai % cd backend.ai-dev/manager
backend.ai/backend.ai-dev/manager % python -m ai.backend.manager.server --debug
backend.ai % cd backend.ai-dev/webserver
backend.ai/backend.ai-dev/webserver % python -m ai.backend.web.server
```
3. Run `backend.ai-client`.
```zsh
backend.ai % cd backend.ai-dev/client-py
backend.ai/backend.ai-dev/client-py % source env-local-admin-api.sh
backend.ai/backend.ai-dev/client-py % backend.ai run python -c "print('Hello World\!')"
```

**Expected behavior**
Run properly without any error.

**Screenshots**
<img width="682" alt="image" src="https://user-images.githubusercontent.com/14137676/168035194-1231a09a-cdb7-4ac1-835f-3faac33af0c5.png">

**Client:**
 - OS: macOS 12.3.1
 - App version: -
 - Browser version: -
 - Python version: 3.9.10
 - NodeJS version: -

**Server:**
 - OS: macOS 12.3.1
   - Output of `uname -a`: Darwin lablupui-MacBookPro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
 - Backend.AI version: 21.09
 - Python version: 3.9.10
 - Installation method: used scripts/install-dev.sh

**Additional context**
https://github.com/lablup/backend.ai-manager/blob/4f5f82ee76b569414af9b66459287098146fc57f/src/ai/backend/manager/config.py#L790-L805
IMHO, this code block has a potential error that can always happen when `raw_min_value` is **not** `None`. Therefore, I suggest to change code as below:
### Current
```python
for slot_key, slot_range in resource.items():
    slot_unit = slot_units.get(slot_key)
    if slot_unit is None:
        # ignore unknown slots
        continue
    raw_min_value = slot_range.get('min')
    if raw_min_value is None:
        min_value = Decimal(0)
    raw_max_value = slot_range.get('max')
    if raw_max_value is None:
        max_value = Decimal('Infinity')
    str2num_func = BinarySize.from_str if slot_unit == 'bytes' else Decimal
    if not isinstance(min_value, Decimal):
        min_value = str2num_func(raw_min_value)
    if not isinstance(max_value, Decimal):
        max_value = str2num_func(raw_max_value)
```
### New
```python
for slot_key, slot_range in resource.items():
    slot_unit = slot_units.get(slot_key)
    if slot_unit is None:
        # ignore unknown slots
        continue
    str2num_func = BinarySize.from_str if slot_unit == 'bytes' else Decimal
    raw_min_value = slot_range.get('min')
    if raw_min_value is None:
        min_value = str2num_func(raw_min_value)
    else:    # if (raw_min_value := slot_range.get('min')) is not None:
        min_value = Decimal(0)
    raw_max_value = slot_range.get('max')
    if raw_max_value is None:
        max_value = str2num_func(raw_max_value)
    else:    # if (raw_max_value := slot_range.get('max')) is not None:
        max_value = Decimal('Infinity')
```

**Comment by achimnol** [comment]
Please take a look! @kyujin-cho

**Comment by kyujin-cho** [comment]
Good catch. As you've mentioned, this issue won't be reproduced on branches other than `21.09`. I'll add a fix PR for this issue.
