### ISSUE TITLE
Manager and Agent halt in starting the services without any error message when an incorrect Redis URL is configured

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#424]
The Redis URL is configured in Etcd at `config/redis/addr`. When this URL is incorrectly specified, Manager and Agent services just halt in launching the services without error messages. It is quite hard to know that the root cause of the stuck is misconfigured Redis URL.

It would be good to print an error log when the services cannot start due to the incorrect Redis URL.

### How to reproduce

* Prepare a local Backend.AI services and check the Manager and Agent starts without problem.
* Change the Redis URL from the etcd.
```shell
cd manager
backend.ai mgr etcd put config/redis/addr <incorrect-redis-url>
```
* Restart the Manager or Agent.
* The service should stuck in the middle of the loading, without any error messages.
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/7539358/169002983-5619d9b2-75bc-44fe-90bf-8e2791da2946.png">

**Comment by rapsealk** [comment]
I think we have to add an explicit check after `aioredis.Redis.from_url()` which is used to get a `aioredis.client.Redis` object in
https://github.com/lablup/backend.ai-common/blob/8aafb0db8d13289f8f12049e8edcb67c3fc60007/src/ai/backend/common/redis.py#L448-L485

`aioredis.client.Redis` does not check for connection in its constructor: https://github.com/aio-libs/aioredis-py/blob/a28e0e9a21f6b645952d888e65f29b433218fba5/aioredis/client.py#L833-L913
