### ISSUE TITLE
Run backend.ai agent error on  'btrfs', Linux filesystem 

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai#454]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.
Run backend.ai agent error on 'btrfs', Linux filesystem with Fedora Core 35 

```
2022-06-09 11:51:53.906 ERROR ai.backend.agent.stats [888587] collect_node_stat(): gather_node_measures() error
Traceback (most recent call last):
  File "/home/dhsung/backend.ai/src/ai/backend/agent/docker/intrinsic.py", line 384, in gather_node_measures
    await loop.run_in_executor(None, get_disk_stat)
  File "/home/dhsung/.pyenv/versions/3.10.4/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/dhsung/backend.ai/src/ai/backend/agent/docker/intrinsic.py", line 374, in get_disk_stat
    dstat = os.statvfs(disk_info.mountpoint)
PermissionError: [Errno 13] Permission denied: '/var/lib/docker/btrfs'
```

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. install 'backend.ai' using pants
2. run backend.ai agent 
3. See error

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.
Successfully running backend.ai agent

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.
<img width="932" alt="스크린샷 2022-06-09 오후 1 10 48" src="https://user-images.githubusercontent.com/20002/172764223-3adc1fc7-7d78-4dfe-97ba-dfae3b079cd3.png">
<img width="973" alt="스크린샷 2022-06-09 오후 1 03 10" src="https://user-images.githubusercontent.com/20002/172764231-abf2e484-5f2e-486a-b8ee-7415bd91b965.png">

**Server:**
 - OS: Fedora Core 35
   - Output of `uname -a`: `Linux fedora 5.14.10-300.fc35.aarch64 #1 SMP Thu Oct 7 20:32:40 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
 - Backend.AI version: 22.06.0.dev3
 - Python version: 3.10.4
 - Installation method: used scripts/install-dev.sh

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

I'm also found the issue on openSUSE .

Currently, Many Linux distributions default filesystem has chosen 'btrfs'. So, I wrote down the issue.

**Comment by achimnol** [comment]
@studioego Please recreate the PR in this repository.

**Comment by studioego** [comment]
I got it.
