### ISSUE TITLE
Move `check_scaling_group()` predicate check to a precondition check in `enqueue_session()`

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#500]
Just like lablup/backend.ai-manager#504.

Then, there will be no more `permanent=True` predicate check results and all predicates will become "temporary", which means that cluster state changes such as termination of existing sessions may flip the results.

**Comment by fregataa** [comment]
https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/scheduler/predicates.py#L290

What is the usage of `PendingSession.target_sgroup_names`? I cannot find where and how to use it.
