### ISSUE TITLE
Naver cloud platform’s price table

### ISSUE THREAD

**Issue by mihilt** [lablup/backend.ai#535]
I'm not sure which repo should I make an issue about this problem, but I think here is the most proper so i write it in here.

It’s not much critical problem, but it seems to be something wrong with [Backend.AI](http://backend.ai/)’s price table on naver cloud platform

![image](https://user-images.githubusercontent.com/50368758/178185207-bfc9c836-66a5-4e9a-96f1-b8b3ceee47a2.png)
[https://www.ncloud.com/marketplace/backend-ai](https://www.ncloud.com/marketplace/backend-ai)

**Comment by inureyes** [comment]
@mihilt  Thank you for your report. We contacted NCP and solved this issue. :D
