### ISSUE TITLE
Add an explicit warning and check for `node` & `npm` availability in `install-dev.sh`

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#553]
When given `--editable-webui`, the installer script blindly tries to invoke `npm`.
Let's check its availability and show an explicit prerequisite warning message like other checks for Python, Docker, and etc.

**Comment by ahmednreldin** [comment]
Hello achimnol, 
i have created a PR  #561 with the required checking 
tell me if something need further improve 
Thanks

**Comment by studioego** [comment]
@achimnol  & @kyujin-cho  I have a question.

I submitted the checking npm & nodejs code in install-dev.sh.

https://github.com/lablup/backend.ai/commit/f09f37801cfaa9873c85cc9db2d9388e0cf2b7f1

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/20002/212256638-68e39869-b769-4110-9080-544769f50583.png">

In this situation, If node & npm is not installed,  should I "end the installing process in a shell script" or "pass and not install webui only"?

**Comment by studioego** [comment]
According to @achimnol 's opinion, From now on, It'll go more minimalize install-dev.sh in Backend.AI
The install-dev.sh is as follows: If possible, just setup the pants after cloning, install some packages with pip and run `./backend.ai mgr start-server`. (future plan)
He said that modifying webui needs some time to think.
`./backend.ai web start-server` 
make it automatic to do npm install, etc. or git clone webui there(after detecting dev-mode). etc.
