### ISSUE TITLE
feat: Update `query_accessible_vfolders()` to include shared-by/shared-with flags in the result

### ISSUE THREAD

**Issue by agatha197** [lablup/backend.ai#568]
**Is your feature request related to a problem? Please describe.**
Users cannot easily distinguish between private folders, folders shared by me, or folders shared by others.

**Describe the solution you'd like**
Update query_accessible_vfolders() to include shared-by/shared-with flags in the result and apply them to the virtual folder's query filter.

**Additional context**
- If there is a row with a `vfolder_id` whose id matches in the `vfolder_permissions` table, the `shared_by_me` is true.
- If there is a row with a `user_id` in the `vfolder_permissions` table that matches the person who requests `user_id`, you can reversely refer to the vfolder table to get the `shared_with_me` information.

**Comment by achimnol** [comment]
This is superseded by #1955.
