### ISSUE TITLE
Introduce vfolder status

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#575]
For storage-proxy operations that takes a long time, such as vfolder clones and deletion, we need to prevent user access in the meanwhile.

Let's introduce vfolder status to allow or deny user's access to individual vfolders.  For example: `READY`, `CLONING`, `DELETING`.

We also need to consider preventing start of the deletion operation when the target vfolder is being mounted to one or more sessions.

Q: When a vfolder is being cloned, should we block the access to the source vfolder as well?

**Comment by soheeeeP** [comment]
@achimnol Can I try this issue if no one has assigned it yet?
