### ISSUE TITLE
change exit code from -1 to 1

### ISSUE THREAD

**Issue by jangjichang** [lablup/backend.ai#580]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.
There's no bug. It is a proposal to follow a convention.

Why don't you change the exit code from -1 to 1?

https://github.com/lablup/backend.ai/blob/main/scripts/install-dev.sh#L568

refernece for exit code: https://tldp.org/LDP/abs/html/exitcodes.html

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

**Client:**
 - OS: [e.g. macOS 10.14, Windows 10 (1903)]
 - App version: [e.g. 19.08.3] (if you are using a GUI client app)
 - Browser version: [e.g. Chrome 76, Safari, Edge] (if you are using a GUI web console)
 - Python version: [e.g. 3.7.4] (if you are using the Python SDK)
 - NodeJS version: [e.g. 12.0] (if you are using the Javascript SDK)

**Server:**
 - OS: [e.g. Ubuntu 18.04, CentOS 7.6, macOS 10.14]
   - Output of `uname -a`: [e.g. `Linux node01 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`]
 - Backend.AI version: [e.g. 19.09.0]
 - Python version: [e.g. 3.6.8]
 - Installation method: [e.g. on-premise, using cloud.backend.ai service, used scripts/install-dev.sh]

**Additional context**
추가적으로 문제 상황을 설명할 수 있는 다른 맥락을 기술해주세요.

**Comment by jangjichang** [comment]
@kyujin-cho 

https://github.com/lablup/backend.ai/pull/511

**Comment by kyujin-cho** [comment]
Oops, you've got it right. Would you mind creating a PR to resolve this issue?

**Comment by jangjichang** [comment]
I will nake PR. Thanks for check.
