### ISSUE TITLE
/scripts/install-dev.sh help massage has misspelld word

### ISSUE THREAD

**Issue by qkoo0833** [lablup/backend.ai#583]
**Describe the bug**
문제가 발생하는 상황에 대한 요약 설명을 적어주세요.

When I receive a help message of --enable-cuda and --enable-cuda-mock from  ' install-dev.sh -h ' ,
'Tensorflow' is spelled incorrectly like 'Tenosrflow'.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:

1. run './scripts/install-dev.sh -h'

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

<img width="443" alt="image" src="https://user-images.githubusercontent.com/49744571/180620619-552088b0-1136-41a3-a6c8-cb7d48dca616.png">

**Server:**
 - OS: macOS12.4
   - Output of `uname -a`: Darwin Kooshui-MacBookPro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64
 - Backend.AI version: [e.g. 19.09.0]
 - Python version: [e.g. 3.6.8]
 - Installation method: scripts/install-dev.sh

**Comment by qkoo0833** [comment]
Can I make PR to correct this word spelling?

**Comment by rapsealk** [comment]
Thank you for the reporting!
Please feel free to make a PR.
