### ISSUE TITLE
If Linux distribution system Python version is 3.6 and older, show the 'capture_output' parameter error on  'check-docker.py'.

### ISSUE THREAD

**Issue by studioego** [lablup/backend.ai#607]
**Describe the bug**
If Linux distribution system Python version is 3.6 and older, show the 'capture_output' parameter error on  'check-docker.py'.

Some Linux distribution's default system Python version is 3.6. such as  CentOS7, 8, 9 and  openSUSE Leap 15.x versions. 

After checking "install_script_deps", checking docker using "scripts/check-docker.py"
https://github.com/lablup/backend.ai/blob/main/scripts/install-dev.sh#L543

```console
Detected Docker installation: System package (20.10.17)
Traceback (most recent call last):
  File "scripts/check-docker.py", line 108, in <module>
    main()
  File "scripts/check-docker.py", line 90, in main
    proc = run(['docker', 'compose', 'version'], capture_output=True, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

https://github.com/lablup/backend.ai/blob/main/scripts/check-docker.py#L90
Python3's subprocess.run() parameter `capture_output` added in Python version 3.7

Below is the details of Python3's subprocess module.
https://docs.python.org/3.10/library/subprocess.html#using-the-subprocess-module
"Changed in version 3.7: Added the text parameter, as a more understandable alias of universal_newlines. Added the capture_output parameter."

**To Reproduce**
1. try to install Backend.AI using 'script/install-dev.sh'
2. See error

**Expected behavior**
Successfully installed Backend.AI

**Screenshots**
![openSUSE-Leap-15 4_aOUde2lGqG](https://user-images.githubusercontent.com/20002/181193847-fceedb2a-3880-4ed1-8045-3e9d7fd91eae.png)

```console
Detected Docker installation: System package (20.10.17)
Traceback (most recent call last):
  File "scripts/check-docker.py", line 108, in <module>
    main()
  File "scripts/check-docker.py", line 90, in main
    proc = run(['docker', 'compose', 'version'], capture_output=True, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
dhsung@DESKTOP-042UROI:~/backend.ai> pyenv install 3.10.5
Downloading Python-3.10.5.tar.xz...
-> https://www.python.org/ftp/python/3.10.5/Python-3.10.5.tar.xz
Installing Python-3.10.5...

BUILD FAILED (openSUSE Leap 15.4 using python-build 20180424)

Inspect or clean up the working tree at /tmp/python-build.20220727153153.5893
Results logged to /tmp/python-build.20220727153153.5893.log

Last 10 log lines:
  File "/tmp/python-build.20220727153153.5893/Python-3.10.5/Lib/ensurepip/__init__.py", line 277, in _main
    return _bootstrap(
  File "/tmp/python-build.20220727153153.5893/Python-3.10.5/Lib/ensurepip/__init__.py", line 193, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
  File "/tmp/python-build.20220727153153.5893/Python-3.10.5/Lib/ensurepip/__init__.py", line 93, in _run_pip
    return subprocess.run([sys.executable, '-W', 'ignore::DeprecationWarning',
  File "/tmp/python-build.20220727153153.5893/Python-3.10.5/Lib/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/python-build.20220727153153.5893/Python-3.10.5/python', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmph78hz_r3/setuptools-58.1.0-py3-none-any.whl\', \'/tmp/tmph78hz_r3/pip-22.0.4-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmph78hz_r3\', \'--root\', \'/\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.
make: *** [Makefile:1280: install] Error 1
dhsung@DESKTOP-042UROI:~/backend.ai> vi /tmp/python-build.20220727153153.5893.log
Error detected while processing /usr/share/vim/vim82/suse.vimrc[10]../usr/share/vim/vim82/syntax/syntax.vim[43]..BufRead Autocommands for "*"..script /usr/share/vim/vim82/scripts.vim:
line   30:
E117: Unknown function: dist#script#DetectFiletype
Press ENTER or type command to continue
```

**Server:**
 - OS: openSUSE Leap 15.4
   - Output of `uname -a`: Linux DESKTOP-042UROI 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Backend.AI version: main
 - Python version: 3.6.15
 - Installation method: [e.g. on-premise, using cloud.backend.ai service, used scripts/install-dev.sh]

**Additional context**

**Comment by studioego** [comment]
During install Backend.AI on Oracle Linux 8 (default python version is 3.6.8) with WSL2, It's occur the same issue.

![image](https://user-images.githubusercontent.com/20002/181253756-4ebf9e96-b003-4582-8e2a-290661ae0828.png)

**Comment by studioego** [comment]
Also, almost similar issue on CentOS 7 with python2
![powershell_1aGGgPla8r](https://user-images.githubusercontent.com/20002/181270200-5aa34446-4962-4859-b11c-c633afadc0be.png)

**Comment by studioego** [comment]
On Rocky Linux 8 version, default python version is 3.6.8
![image](https://user-images.githubusercontent.com/20002/181505975-000f183a-014a-474b-9f68-8bf4bb3a81ca.png)

**Comment by achimnol** [comment]
We now run `install-dev.sh` with a static CPython build auto-downloaded via the "boostrapping" procedure, as of #1246.
