### ISSUE TITLE
Update docs for session command example

### ISSUE THREAD

**Issue by qkoo0833** [lablup/backend.ai#631]
<img width="766" alt="스크린샷 2022-08-07 오후 4 36 18" src="https://user-images.githubusercontent.com/49744571/183280602-b1d4e911-2274-4960-9082-a755acb3741c.png">

update: before `backend.ai admin sessions` => after `backend.ai admin session list`

---

<img width="739" alt="스크린샷 2022-08-07 오후 4 43 27" src="https://user-images.githubusercontent.com/49744571/183280709-40cef8a2-805e-4ced-b2f3-d102e1bf69f3.png">

update: before `backend.ai download mysess id_container` => after `backend.ai session download mysess id_container`

**Comment by qkoo0833** [comment]
labeling, `docs` `skip:ci`

**Comment by rapsealk** [comment]
Both labels `skip:ci` and `skip:changelog` are for PRs; for literally skipping ci and towncrier process.
Please feel free to make a PR. It is always welcomed.
If you already made a PR, don't forget to refer this issue!
