### ISSUE TITLE
Support opening local VSCode using remote SSH mode to session containers

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#646]
VSCode has its strength on supporting remote development with its native server-client architecture. Let's make our users able to fire up their local VSCode desktop app to access our session containers (just like GitHub Codespaces) via SSH, similarly to `backend.ai ssh` command.

### Technical background
* Modern desktop operating systems supports declaration of custom URL scheme by applications.
* VSCode uses this feature to make a hyperlink to local files, WSL envs, and remote machines.
  The official document does not reveal the exact format but here I found it:
  - `vscode://vscode-remote/ssh-remote+<url-quoted-username>%3A<url-quoted-assword>@<ip>:<port>/<remote-path-to-open>`
  - The username and password should not contain colon (`:`) because `%3A` (URL-encoded colon) is used to split them.

### Example
![image](https://user-images.githubusercontent.com/555156/184075059-ce90ad1b-be72-471c-8b1e-c7db58654466.png)

### Let's do:
* [x] **agent**: Generate a random alpha-numeric password in `entrypoint.sh` and store it as `.passowrd` in the home directory (just like `id_container`) when the session container starts.
* [x] **manager**: Add `.password` as one of the prohibited names for vfolders.
* [ ] **webui**: Add a "Open in VSCode desktop app" button in the app launcher.
  - Using in-kernel file download API, take the password of the session.
  - Open the URL fabricated like above, using the wsproxy host and port number.

**Comment by studioego** [comment]
I have one question. 
Should the `.password` file be generated at the first execution or at every run?

**Comment by studioego** [comment]
For the first time, I committed the agent's feature, 'Gerenate & store a random alpha-numeric password'.
https://github.com/lablup/backend.ai/commit/0062ecfd67857bf9a7564e3ac0904f559826a2a3

**Comment by studioego** [comment]
In my opinion, Manager's dot files(starts with `.` eg. `.bashrc`) is already prohibited names for vfolders .

https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/api/vfolder.py#L271
https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/api/vfolder.py#L1299
https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/api/vfolder.py#L1933

**Comment by studioego** [comment]
Now I try to add a "Open in VSCode desktop app" button in the app launcher.

**Comment by studioego** [comment]
I generated .password file when the session container starts.
However, .password file permission is root, because when the session container starts, the file is generated by root permission.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/20002/188573092-643e13eb-f66a-4928-ab91-0aed5fe07496.png">
So, After generating .password file, Should I change the .password file permission, as a 'work/dialout'?

**Comment by achimnol** [comment]
As long as the user (`work`) can read it, I think it is better to let it stay as `root`-owned to prevent mistakenly removal or modification.
The access to the password file from the client side will be done by the agent using the kernel file download API, so it wouldn't affect the operation.

FYI) `dialout` seems to be a misconfigured name.  Since [`entrypoint.sh`](https://github.com/lablup/backend.ai/blob/main/src/ai/backend/runner/entrypoint.sh) auto-created both `work` user and `work` group, so it should appear as `work`.

**Comment by studioego** [comment]
It's a working thread. 
I generated vs code icon. 
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/20002/189848971-b1e4d379-240e-4265-be02-24010765076a.png">
then, I'll try to connect VS Code

**Comment by studioego** [comment]
After the Webui pr  https://github.com/lablup/backend.ai-webui/pull/1487 is closing, I close the issue.
