### ISSUE TITLE
Streamline self-bootstrapping of Pants in Apple Silicon Macs

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#690]
"Some" Apple Silicon Mac users have suffered from the installation process which triggered the source build of Pants although their platform is the officially supported one (MacOS + arm64) with the official prebuilt wheel package of `pantsbuild-pants`.

After digging down on a Mac that reproduces this issue, we figured out the reason:
* [`pantsbuild-pants` in PyPI](https://pypi.org/project/pantsbuild.pants/2.13.0rc0/#files) has 3.7/3.8/3.9 wheels for macOS + x86-64 but there is only 3.9 wheel for macOS + arm64.
* macOS Monterey's system Python is 3.8.9.
* Homebrew's latest Python installation uses 3.10.6.
* `./pants version` fails because it could not find the matching interpreter version, 3.9, from Homebrew's Python and the system Python for the list of prebuilt wheels in PyPI.
* `.pants.env` is read by the actual Pants process and `./pants-local` only, but *not* by the `./pants` script itself. So, setting `PY` or `PYTHON` environment variables there had no effects to whether to install or build Pants.

Combined with all above, depending on when you have run `brew install python3` (e.g., last year...), your homebrew *may* have 3.9, and this case, it has worked flawlessly.  Or, if you have run `pyenv local 3.9.xx` in the cloned working directory, it also has worked flawlessly.  Otherwise, you may have suffered from source-build requirements of Pants.

To resolve this, we need to do the followings:
* [x] **./pants**: Let's update it to [the latest version](https://www.pantsbuild.org/docs/manual-installation) as it now has the official support for the env-var customization for the script itself:
```diff
diff --git a/pants b/pants
index 5c84ca4e..ed46bbea 100755
--- a/pants
+++ b/pants
@@ -12,6 +12,12 @@

 set -eou pipefail

+# Source any custom bootstrap settings for Pants from PANTS_BOOTSTRAP if it exists.
+: ${PANTS_BOOTSTRAP:=".pants.bootstrap"}
+if [[ -f "${PANTS_BOOTSTRAP}" ]]; then
+  source "${PANTS_BOOTSTRAP}"
+fi
+
 # NOTE: To use an unreleased version of Pants from the pantsbuild/pants main branch,
 #  locate the main branch SHA, set PANTS_SHA=<SHA> in the environment, and run this script as usual.
 #
```

* [x] **scripts/install-dev.sh**: Let it search pyenv-based Python 3.9 before running `./pants version` and put it to `./.pants.bootstrap` as `PYTHON` env-var if found the match.
* [x] **.gitignore**: Add `/.pants.bootstrap`.
* [x] **docs**: Update the source installation manual to describe this pitfall and explicitly recommend check and install Python 3.9 via `pyenv`.

**Comment by achimnol** [comment]
Once https://github.com/pantsbuild/pants/pull/16484 is done and we migrate to the 2.14 release line of Pants, we won't need to install two separate Python versions for Pants and our project. Let's see how it goes on.

**Comment by chrisjrn** [comment]
@achimnol I'd be very happy to see how well it works for you. Note that the initial few releases will be experimental only.

**Comment by Eric-Arellano** [comment]
*Note that this will be Pants 2.15. 2.14 already had its first alpha release, so now `main` is 2.15. This means likely ~1.5 months away from a stable release. We would absolutely love your feedback though on testing this out.

**Comment by achimnol** [comment]
TIP) For those who wants to check the Python versions in your system:
```console
$ for p in $(which -a python) $(which -a python3); do echo "$p -> $($p --version)"; done
/Users/joongi/.pyenv/shims/python -> Python 3.10.5
/Users/joongi/.pyenv/shims/python3 -> Python 3.10.5
/opt/homebrew/bin/python3 -> Python 3.9.13
/usr/bin/python3 -> Python 3.8.9
```
