### ISSUE TITLE
Add the commit history between releases in the release notes

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#691]
Let's append the actual commit history for each release by updating `scripts/extract-release-changelog.py`.
Now we can skip changelogs for specific PRs, but sometimes we may still want to inspect the full history of commits.

The generated URL should look like:
`https://github.com/lablup/backend.ai/compare/22.09.0b4...22.09.0b5` (The result: https://github.com/lablup/backend.ai/compare/22.09.0b4...22.09.0b5)

This requires determining the *previous* release tag name in the script.

**Comment by 100sun** [comment]
@kyujin-cho You might close this issue because the above PR has already merged.
