### ISSUE TITLE
client cannot fetch request to webserver

### ISSUE THREAD

**Issue by fregataa** [lablup/backend.ai#706]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

main

### Describe the bug

webserver cannot handle requests from client, since the requests do not have `X-BackendAI-Encoded` in header.
the payload of any request from client changes to an empty list.

### To Reproduce

1. run webserver. `./py -m ai.backend.web.server`
2. set environment variables, `source env-local-admin-session.sh`
3. try login, `./backend.ai login` and type any username and password.

### Expected Behavior

successfully login and can request any backend.ai client commands.

### Anything else?

the webserver should be able to handle requests from client

**Comment by chapaith** [comment]
Hi there, Can I work on this issue?

**Comment by fregataa** [comment]
> Hi there, Can I work on this issue?

yes. there is no one assigned yet. you can assign yourself on this issue

**Comment by achimnol** [comment]
We need to extend/continue this PR: #835 493

**Comment by leejiwon1125** [comment]
![image](https://user-images.githubusercontent.com/110564003/211973898-0e83362a-3be9-44e9-966c-442778b62ada.png)
Issue solved!
