### ISSUE TITLE
Cannot update admin 

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai#717]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

dcf198c44b07aa348cf719772000c51e0ba5f6ac

### Describe the bug

If the user is admin or superadmin, it cannot update any option because of the below error.
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/28584164/188873668-58ea8eea-daa5-4689-8625-c197bbdc5887.png">

### To Reproduce

1. Add an admin or superadmin user.
2. Update info of that user using `./backend.ai admin user update [OPTIONS] EMAIL`.
3. See an error.

### Expected Behavior

Update option without error (admin or superadmin previleged).

### Anything else?

I think [these codes](https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/models/user.py#L696-L697) are the problem.

**Comment by h20220025** [comment]
hey @Sujin-Kim1 i am looking forward to work on this issue.

**Comment by Sujin-Kim1** [comment]
> hey @Sujin-Kim1 i am looking forward to work on this issue.

@fregataa had already handled it. #718 
Sorry and appreciate it!
