### ISSUE TITLE
cannot install because python version

### ISSUE THREAD

**Issue by jangjichang** [lablup/backend.ai#722]
### What Operating System(s) are you seeing this problem on?

macOS (Intel)

### Backend.AI version

22.09.0b1

### Describe the bug

i cannot install using scrips/install-dev.sh command

because pyenv does not support 3.10.7 version

### To Reproduce

run scrips/install-dev

### Expected Behavior

install successfully.

### Anything else?

i try to update pyenv. `brew update && brew upgrade pyenv` 

but still cannot install python 3.10.7

how about downgrade pants.toml interpreter_constraints version?

**Comment by kyujin-cho** [comment]
Though pyenv hasn't published new release with support for 3.10.7 yet, they have included it on main branch (pyenv/pyenv#2454). Please reinstall pyenv by using [pyenv installer](https://github.com/pyenv/pyenv-installer) instead of homebrew version and try again.

**Comment by achimnol** [comment]
pyenv does not automatically pick up its own updates.
You may try https://github.com/pyenv/pyenv-update to easily update your installation of pyenv by just `pyenv update`.

**Comment by achimnol** [comment]
I think the above answers should be sufficient to resolve your issue.
If you have futher questions, please feel free to reopen the issue.
