### ISSUE TITLE
Auto-generate and auto-commit news fragment from PR title

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#742]
It seems better to describe that you need to `git pull` after creating the PR instead of to teach how to write news fragments for new developers and external cotnributors.

Let's do the followings:

* [ ] Auto-generate and auto-commit the news fragments when the PR title is changed using GitHub Actions.
  - Take the extension of news fragment files from the matching labels.
  - The workflow should report "failure" if there is no matching label.
  - We may need to reorganize the labels in the repo configuration.
  - When changed, update only the news fragment file that has the same content of previous PR title and the label-matching extension.
    - We may still need to manually insert additional news fragments (e.g., when there are breaking changes).
    - We may still need to add more details to the news fragment, while this action will provide a good initial value.

Let's change our rule as well:

* **Don't** add conventional-commit-style prefixes to the PR titles (e.g., `fix:`, `feat:`, etc.) and just use explicit PR labels.

**Comment by Yaminyam** [comment]
I wonder if it is generating a news fragment based on the label included in the PR title or referring to the label of the labels function of github.

**Comment by Yaminyam** [comment]
Replaced by #989
