### ISSUE TITLE
Scalability consideration for abusing reports

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai#749]
### Main idea

This is a (potential) follow-up issue for #737.     
The downside of current implementation is that manager need to perform RPC call for each container. When number of container rises, this can cause a performance issue to both manager and agent. We need to fix this.   
Some possible options are:
- make agent scan abusing report path periodically, and update redis (or any other state manager) if new container is found
- same, but use heartbeat as a report channel

Any future ideas are welcome.

**Comment by fregataa** [comment]
how about adding abusing report info in any RPC call response from agent?
