### ISSUE TITLE
Show user-friendly error msg when invalid IP address passed as a client IP filter

### ISSUE THREAD

**Issue by Sujin-Kim1** [lablup/backend.ai#773]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

22.09.0

### Describe the bug

If the user inputs invalid values, the manager or client gives an error message including an SQL error statement. Let's remove the SQL statements and provide a user-friendly error syntax.

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/28584164/193959733-abc64410-395a-4e76-b08d-b58846a23042.png">

### To Reproduce

Set anyone's allowed IP 1.2.3.4/16. It occurs with unexpected error messages including an SQL statement.

### Expected Behavior

Give only a human-friendly error message.

**Comment by achimnol** [comment]
If we could extract the validation result from the database error codes or messages, we should transform such results into `InvalidAPIParameters` exception.

If we could configure whether to include the SQL statements in the error messages generated by the database engine or adaptor, we should hide them in the *production* environments, while showing them in the development setups with explicit debug flags.
