### ISSUE TITLE
Inhibit mounted vfolder deletion

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai#776]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

21.03

### Describe the bug

For now, there's no explicit error that comes out when deleting virtual folder that is mounted to one or more sessions, which would bring a serious security hole. 

### To Reproduce

1. Create a virtual folder
2. Create a session with the folder created in step 1 mounted
3. Delete the folder created in step 1
4. Try to access the folder inside the session created in step 2 (with ttyd, etc.)
5. See the error.

### Expected Behavior

When virtual folder is mounted to one or more sessions, then deleting the mounted folder shall not be allowed.

### Anything else?

It's been handled in former repo (https://github.com/lablup/backend.ai-manager/pull/417), but It was on stale status for a while, and now It needs to be resolved.

**Comment by fregataa** [comment]
Resolved by #2036
