### ISSUE TITLE
Allow override of region of agennts

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#79]
Currently agents provide a `region` field when sending heartbeats to the manager.
Let's allow admins to override it.

NOTE: It's already formatted as "{platform}/{region}" (e.g., "amazon/ap-northeast-2")
where the slash and the region part is optional (e.g., "local").

* Agent
  - [ ] Allow manual override of the `region` value in toml instead of auto-detection.

**Comment by kyujin-cho** [comment]
https://github.com/lablup/backend.ai-agent/blob/master/src/ai/backend/agent/server.py#L435
Already Implemented!
