### ISSUE TITLE
backend.ai CLI fails to load `.env` file

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai#792]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

22.09.1

### Describe the bug

Seems like Backend.AI CLI is failing to load `.env` file when CLI is installed via pip.

### To Reproduce

1. Install Backend.AI CLI with `pip install backend.ai-client`
2. Create `.env` file with environments `BACKEND_ACCESS_KEY`, `BACKEND_SECRET_KEY`, `BACKEND_ENDPOINT` and `BACKEND_ENDPOINT_TYPE`
3. Run `backend.ai config`
<img width="417" alt="image" src="https://user-images.githubusercontent.com/2904494/195768680-df781598-1606-46f4-aa4c-72c5f2ba901b.png">

### Expected Behavior

`backend.ai config` should print access key information as provided on `.env` file

**Comment by achimnol** [comment]
Please refer #800 on why this happens and how to fix it.
