### ISSUE TITLE
Update outdated `README.md` badges

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai#793]
### Main idea

Since our README‘s badges related to PyPI package points `backend.ai` package, which is abandoned after we’ve migrated to mono-repo, is referencing outdated informations.
![IMG_0070](https://user-images.githubusercontent.com/2904494/196345430-551621c3-cc23-42d4-8d0f-b974a8db5b2e.png)
I think we can resolve it by just change it to point `backend.ai-manager`.

**Comment by hekang42** [comment]
이슈 할당 요청드립니다.

**Comment by hekang42** [comment]
@lizable

**Comment by hekang42** [comment]
Can i do this issue? @lizable
