### ISSUE TITLE
Typo on session commit status API reponse

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai#795]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

22.09.2

### Describe the bug

Response of `GET /session/{session_name}/commit` API has typo.
![IMG_0071](https://user-images.githubusercontent.com/2904494/196350027-454ece86-f2ff-449c-b144-9597152ea727.png)

### Expected Behavior

`stats` have to be `status`.

**Comment by 100sun** [comment]
I want to resolve this issue.  @lizable
