### ISSUE TITLE
Add a kernel environment variable to specify local rank

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#802]
### Main idea

Each session container embeds useful environment variables for cluster session:
```shell
BACKENDAI_CLUSTER_HOST="main1"
BACKENDAI_CLUSTER_HOSTS="sub1,main1"
BACKENDAI_CLUSTER_IDX="1"
BACKENDAI_CLUSTER_REPLICAS="main:1,sub:1"
BACKENDAI_CLUSTER_ROLE="main"
BACKENDAI_CLUSTER_SIZE="2"
```

However, there is no variable that can be used as the local index of the current container. It would be helpful to add such a variable for multi-node training scripts to auto-detect the current container's local rank.

### Alternative ideas

Add a new variable like`BACKENDAI_CLUSTER_LOCAL_RANK`. The value of it would be `0` for the `main1` container, `1` for the `sub1` container, `2` for the `sub2` container, etc.

**Comment by Atralupus** [comment]
Hi👋 Can I get this issue?

**Comment by Atralupus** [comment]
@lizable

**Comment by Atralupus** [comment]
Hi, Is there anyone who can review this [PR](https://github.com/lablup/backend.ai/pull/826)?

**Comment by fregataa** [comment]
`BACKENDAI_CLUSTER_IDX` is already used as an index. what is the difference between `BACKENDAI_CLUSTER_IDX` and local rank?
