### ISSUE TITLE
Unable to see invited and project virtual (data) folders with CLI

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#809]
### What Operating System(s) are you seeing this problem on?

Linux (aarch64)

### Backend.AI version

22.9.2

### Describe the bug

With `backend.ai-client` package, we can see the available virtual folder list by `backend.ai vfolder list`. However, it only displays the virtual folders that the user created, not the invited and project folders.

### To Reproduce

* Assume there is a user account `user@backend.ai`.
* With another account, create a user folder and share (invite) the folder to the `user@backend.ai`.
* With an admin account, create a project folder.
* With `user@backend.ai` account, execute the following command:
  ```shell
  backend.ai vfolder list
  ```
* It will display the user's own folders, not invited, and project folders.

For example, from Web-UI, I was able to see invited, and project folders as well as my own folders:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/7539358/197223469-a0fe2375-204f-4309-a22b-593198796eed.png">

However, in CLI, I only saw the virtual folders that I have created:
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/7539358/197223513-5b97c031-74e5-4ebe-a681-696b0522ad51.png">

### Expected Behavior

With the CLI command, we need to see invited and project folders as well.

**Comment by achimnol** [comment]
This is superseded by #1955.
