### ISSUE TITLE
Update README.md on documentation guide about building PDF document

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai#810]
### Main idea

Currently, The section about "Building PDF document" is empty. Let's add how-to-do it with simple but essential guide for that.
Here's the link for needs improvement.
https://github.com/lablup/backend.ai/tree/main/docs#-building-pdf-document-wip-

**Comment by theshubhamgour** [comment]
Please assign this to me @lizable

**Comment by TheClerici** [comment]
Hello, if still needed I can add it
