### ISSUE TITLE
Fill out translation for Concepts part of Backend.AI Core Documentation

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai#813]
### Main idea

There is a lot of missing documentation that needs translation, especially from English to Korean, Which brings a hard time to understand the documentation who cannot understand English very well (for Koreans).
Let's fill out the Korean translation for the Concepts part.
Here's the part that needs translations.
https://github.com/lablup/backend.ai/tree/main/docs/locales/ko/LC_MESSAGES/concepts

**Comment by chichoon** [comment]
Can i do this issue? @lizable
