### ISSUE TITLE
Let's add installation guide for WSL2 in documentation

### ISSUE THREAD

**Issue by lizable** [lablup/backend.ai#818]
### Main idea

Currently, Backend.AI is developed and tested under only *NIX-compatible platforms (Linux or macOS), but we have a chance to apply Backend.AI to WSL2 which is apparently Linux OS. Let's add an extra guide at the bottom of this section(https://docs.backend.ai/en/latest/install/development-setup.html).

> ⚠️ NOTE:
> In this installation guide, unlikely other OS, you may need to specify the exact status (the version of OS, Docker, Python, etc.)

**Comment by theshubhamgour** [comment]
Please Assign this to me @lizable

**Comment by ArnavScripts** [comment]
done #830

thank you for giving me this opportunity!

**Comment by achimnol** [comment]
Replaced and completed with #1722.
