### ISSUE TITLE
Extending an interactive drag-and-drop feature to moving files

### ISSUE THREAD

**Issue by dumaaan** [lablup/backend.ai#86]
During the manual upload of the files to my folders on Backend.AI, I have noticed that a drag-and-drop feature works only on uploading the files, and there is no such option for moving the _already uploaded_ files to another folder.

In other words, the current solution for manually moving files seems to be deleting and reuploading the file to the necessary folder again.

It would be nice to have a drag-and-drop option extended for moving the files, which would enhance UX when working with Backend.AI client interface.

An alternative solution to moving the files is to start another session on Backend.AI web app and to move files through terminal command line. But this solution takes some time and is not an effective solution to the problem.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1159751085623729/1159757028655052) by [Unito](https://www.unito.io/learn-more)

**Comment by achimnol** [comment]
We could extend this issue as "Improvements of general file-browser functionality".

**Comment by achimnol** [comment]
Now this is done by the filebrowser containers.
