### ISSUE TITLE
`./backend.ai login` command not working

### ISSUE THREAD

**Issue by jopemachine** [lablup/backend.ai#877]
### What Operating System(s) are you seeing this problem on?

macOS (Apple Silicon)

### Backend.AI version

22.09.4

### Describe the bug

```
User ID: admin@lablup.com
Password: 
✘ BackendAPIError: 400 Bad Request
  You must provide the username field.
```

It said `username` field is missing.

### To Reproduce

```
$ source env-local-admin-session.sh
$ ./backend.ai login
```

**Comment by rapsealk** [comment]
Guess it is related to https://github.com/lablup/backend.ai/pull/626

**Comment by fregataa** [comment]
maybe related to https://github.com/lablup/backend.ai/issues/706

**Comment by leejiwon1125** [comment]
![image](https://user-images.githubusercontent.com/110564003/211974150-3e4a4c7c-cf4a-4989-a802-55f08cfff1e6.png)
Issue solved!
