### ISSUE TITLE
Error while: $./backend.ai mgr fixture populate sample-configs/example-keypairs.json

### ISSUE THREAD

**Issue by kimdarwin** [lablup/backend.ai#884]
안녕하세요. 여기에 문의드려도 되는지 모르겠습니다.
아래 페이지를 보고 따라 설치하였는데 필요한 파일이 없는 것 같습니다.

[Backend.AI Manager with API Gateway]
https://github.com/lablup/backend.ai/blob/main/src/ai/backend/manager/README.md#kernelsystem-configuration

실행한 부분:
Set up the database:
$ ./backend.ai mgr schema oneshot
$ ./backend.ai mgr fixture populate sample-configs/example-keypairs.json

에러 메시지: 
return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'sample-configs/example-keypairs.json'

만약 정식 문의채널을 알려주시면 이 글은 삭제하도록 하겠습니다.
감사합니다.

**Comment by lizable** [comment]
Hi, @kimdarwin I think That part in README is deprecated. Please refer here and change the path :).
https://github.com/lablup/backend.ai/blob/f5cb599f393160c97998458b1b423819746af29f/scripts/install-dev.sh#L784-L787
