### ISSUE TITLE
Add project resource policy

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#89]
Resource policy table (`keypair_resource_policies`) is currently bound _only_ to `keypairs`. Domains and groups (=projects) have their own `total_resource_slots`, `allowed_vfolder_hosts`, and `allowed_docker_registries`, separately. This makes it difficult to calculate unified resource policies considering domain, group, and keypair as a whole.

NOTE: We will soon rename all occurrences of "user" group to **project**.

We need to generalize `keypair_resource_policies` by making it referenced by domain, groups, or any other tables. By doing so, we may be able to unify/merge the calculation of user’s available resources.

- [ ] Rename `keypair_resource_policies` to `resource_policies`
  - Use polymorphic association?
    - https://hackmd.io/@chrisoney/rkNWNTt_d
    - https://docs.sqlalchemy.org/en/20/orm/inheritance.html
  - or, define separate (inherited) tables for domain, project, and keypair?
- [x] Add `allowed_docker_registries` field in `resource_policies`.
- [x] Add ForeignKey `resource_policy` to `domains` and `groups`.
- [x] Remove fields from `domains` and `groups`.
  - `total_resource_slots`
  - `allowed_vfolder_hosts`
  - `allowed_docker_registries`
- [x] Modify resource-related CRUD operations for `domains` and `groups`.
- [ ] Update the `resource_presets` table schema to belong to `resource_policies`
  - Q: Or, should we make it to bleong to `scaling_groups` or both?
- [ ] Add a function or a method to calculate unified allowed resources for requested keypair in `src/ai/backend/manager/models/resource_policy`. Consider domain-/group-/keypair-level resource policies to result in a merged resource policy.
- [x] Replace resource calculation logics in `resource-presets` and scheduler with the above function/method.
- [ ] client-py
  - [ ] Update domain CRUD operations to conform to the manager API changes.
  - [ ] Update group CRUD operations to conform to the manager API changes.
  - [ ] Update resource policy CRUD operations to conform to the manager API changes.
- [ ] Manager-hub should change its UI and interface to correspond to changes above in the manager. 
  - [ ] There should be a separate resource policy page, and domain/group reference the policies by name.
  - [ ] Update domain CRUD operations to conform to the manager API changes.
  - [ ] Update group CRUD operations to conform to the manager API changes.
  - [ ] Update resource policy CRUD operations to conform to the manager API changes.

**Comment by adrysn** [comment]
mis-referenced commit: https://github.com/lablup/backend.ai-manager/commit/02778d0816d4ccaf8034bee1f22ddc75187558c6

**Comment by adrysn** [comment]
I have to remember reference this issue number: https://github.com/lablup/backend.ai-manager/commit/97122e243d755941b8105df495ecf16fb766490a

**Comment by adrysn** [comment]
It's very hard to remember referencing this issue...... https://github.com/lablup/backend.ai-manager/commit/9a11345c17da50e65c3121003e9fb8196704fe79

**Comment by adrysn** [comment]
https://github.com/lablup/backend.ai-manager/commit/4b7781f8c49fb264d495b64c557d7eb41563a075 ...

**Comment by achimnol** [comment]
Resolved by #1354.
