### ISSUE TITLE
Backend.AI Client API library for PHP 7 

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai#9]
* Sorna Client API library for PHP 7

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1159751085623729/1159757314162105) by [Unito](https://www.unito.io/learn-more)

**Comment by achimnol** [comment]
Created [a repo here](https://github.com/lablup/backend.ai-client-php) which will be publicly released after some development.

**Comment by achimnol** [comment]
We won't prioritize this for now.
