### ISSUE TITLE
Recognize partial session ID in CLI command

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai#91]
Backend.AI CLI does not recognize partial session IDs. User have to type full session IDs when running commands like  `backend.ai logs <sess-id>` or `backend.ai rm <sess-id>`.

I think it will be convenient if CLI can understand partial session IDs.

There would be many ways to implement this feature.
* I think it is okay to fetch requester’s available session list to compare their IDs with user provided partial session IDs. This results in additional request to gateway server beforehand main request, but it would be worthwhile.
* I intend no modification on the gateway server.
* Session ID converter should be implemented as an independent function or method, so it is one-liner call from command function. It may be wrapped as a decorator, as well.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1159751085623729/1159756984022007) by [Unito](https://www.unito.io/learn-more)

**Comment by achimnol** [comment]
We could implement shell-specific auto-completion extension with support from Click.
Let's handle this in [backend.ai-cli](https://github.com/lablup/backend.ai-cli) once #35 is done.

**Comment by achimnol** [comment]
refs lablup/backend.ai-client-py#24

**Comment by achimnol** [comment]
This is now implemented and shipped in v20.03 series, via lablup/backend.ai-manager#258.
