### ISSUE TITLE
Use tmux by default for ttyd

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#96]
Suggestion by @inureyes 
 * [x] Let ttyd attach-or-create a tmux session upon startup.
 * [ ] Bring tmux as a static binary that can be run in all kernels.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1159751085623729/1159756966959493) by [Unito](https://www.unito.io/learn-more)

**Comment by achimnol** [comment]
ref) [Building tmux statically](https://gist.github.com/mbreese/b0630195e57874c87ef3611d059d1bc2)

**Comment by adrysn** [comment]
I think the usability shloud also be considered by adapting tmux as the default app for ttyd. For example, vanilla tmux does not support mouse, history scrolling (page up/down, by mouse), and etc. At least, we need to provide the default `.tmux.conf` to make it feel like native ttyd shell environment.
