### ISSUE TITLE
os.cpu_count() returns None in Python session

### ISSUE THREAD

**Issue by ChangHoon-Sung** [lablup/backend.ai#964]
### What Operating System(s) are you seeing this problem on?

Linux (aarch64)

### Backend.AI version

23.03.0dev0

### Describe the bug

OS Detail: Ubuntu(aarch64) VM on macOS 13.1
Tested image: cr.backend.ai/multiarch/python:3.9-ubuntu20.04 (aarch64)

`os.cpu_count()` returns `None` in the Python session.
It also makes `multiprocessing.cpu_count()` returns `None` because it just uses os.cpu_count() for counting.
(https://github.com/python/cpython/blob/074b881e1125bc431ef18681034ba43a9d6e2cb7/Lib/multiprocessing/context.py#L41-L47)

I also checked the other ways to count the number of CPUs in the shell but it seems correct.
(example executed within 1 CPU session)
- `nproc`: 1
- `cat /sys/fs/cgroup/cpuset.cpus`: 0
- `cat /sys/fs/cgroup/cpuset.cpus.effective`: 0
- `lscpu | grep 'CPU(s):'`: 6 (number of VM's core)

### To Reproduce

**Example 1 - quick check**

run `./backend.ai run python 'import os; print(os.cpu_count() is None)'`

<img width="884" alt="ScreenShot 2023-01-09 at 16 51 11@2x" src="https://user-images.githubusercontent.com/37946887/211261522-4c94c73b-f045-493f-a77c-c029d60234ca.png">

**Example 2 - package installation failure**
It makes some package installations fail when they determine the number of jobs or workers using os.cpu_count() or multiprocessing.cpu_count().

run `./backend.ai run python 'pip install line_profiler'`

![ScreenShot 2023-01-09 at 17 02 43@2x](https://user-images.githubusercontent.com/37946887/211265079-6930f7e9-6575-449f-a82b-d54d591a66b8.png)

### Expected Behavior

It should return the number of allocated CPUs on the session.

Example 1 should be `False`
Example 2 should be installed successfully.

### Anything else?

Maybe related with #807

**Comment by kyujin-cho** [comment]
Related to #865.
