### ISSUE TITLE
Add "Ubuntu" case in install-dev.sh 

### ISSUE THREAD

**Issue by leejiwon1125** [lablup/backend.ai#974]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

22.09

### Describe the bug

![image](https://user-images.githubusercontent.com/110564003/212032307-48bc7eef-50b1-4686-8a14-4c7df4ef3eee.png)
in "install-dev.sh" code, there are Debian, RedHat, SUSE, Darwin case but Ubuntu case misses.

See this
![image](https://user-images.githubusercontent.com/110564003/212032722-95cec7b1-56c3-422e-a721-50d1689110cf.png)
there is value 'Ubuntu' in $DISTRO 

### Expected Behavior

Work correctly ./scripts/install-dev.sh

### Anything else?

I think it's because changing of install-dev.sh in three weeks.

**Comment by studioego** [comment]
Ubuntu is the one of Debian-based Linux distributions.
So, Many Debian-based Linux distributions use the Debian package name as the system package name.

If the Backend.AI is not installed or working, it's a critical issue. However, It is installed and works correctly on Ubuntu distributions in x86, aarch64.

In my opinion, It's not an issue for me.

**Comment by rapsealk** [comment]
This issue was found during the investigation of installation problem on GitHub Codespace. It just terminates right after processing the code block below, without any error log.
https://github.com/lablup/backend.ai/blob/86256a831aee3b81e2ca2d026705683be923999d/scripts/install-dev.sh#L566-L603

**Comment by achimnol** [comment]
https://github.com/lablup/backend.ai/blob/29f4a12ecc73a12ab414f72726c08c4568990756/scripts/install-dev.sh#L177

Ubuntu is regarded as the same of Debian.

**Comment by achimnol** [comment]
The issue itself is invalid.
If we can reproduce the codespace setup issue, please open it as another new issue.
